package presentacion.comando;

public enum IDEventos {
	
	 EVENTO_ALTA_SOCIO,
	 ERROR_ALTA_SOCIO,
	 EVENTO_ALTA_NO_SOCIO,
	 ERROR_EVENTO_ALTA_NO_SOCIO,
	 EVENTO_CONSULTA_CLIENTE,
	 ERROR_CONSULTA_CLIENTE,
	 EVENTO_CONSULTA_TODOS_CLIENTES,
	 ERROR_EVENTO_CONSULTA_TODOS_CLIENTES,
	 EVENTO_CONSULTAR_CLIENTE_BORRAR,
	 ERROR_CONSULTAR_CLIENTE_BORRAR,
	 EVENTO_CONSULTAR_CLIENTE_MODIFICAR,
	 ERROR_EVENTO_CONSULTAR_CLIENTE_MODIFICAR,
	 EVENTO_MODIFICAR_CLIENTE,
	 ERROR_MODIFICAR_CLIENTE,
	 EVENTO_BAJA_CLIENTE,
	 ERROR_EVENTO_BAJA_CLIENTE,
	
	 
	 EVENTO_ALTA_ENCARGADO,
	 ERROR_EVENTO_ALTA_ENCARGADO,
	 EVENTO_ALTA_EMPLEADO,
	 ERROR_EVENTO_ALTA_EMPLEADO,
	 EVENTO_CONSULTA_TRABAJADOR,
	 ERROR_EVENTO_CONSULTA_TRABAJADOR,
	 EVENTO_MODIFICAR_TRABAJADOR,
	 ERROR_EVENTO_MODIFICAR_TRABAJADOR,
	 EVENTO_CONSULTA_TODOS_TRABAJADORES,
	 ERROR_CONSULTA_TODOS_TRABAJADORES,
	 EVENTO_CONSULTAR_TRABAJADOR_BORRAR,
	 ERROR_EVENTO_CONSULTAR_TRABAJADOR_BORRAR,
	 EVENTO_CONSULTAR_TRABAJADOR_MODIFICAR,
	 ERROR_EVENTO_CONSULTAR_TRABAJADOR_MODIFICAR,
	 EVENTO_BAJA_TRABAJADOR,
	 ERROR_EVENTO_BAJA_TRABAJADOR,
	
	 
	 EVENTO_ALTA_ARTICULO,
	 ERROR_EVENTO_ALTA_ARTICULO,
	 EVENTO_CONSULTA_ARTICULO,
	 ERROR_EVENTO_CONSULTA_ARTICULO,
	 EVENTO_CONSULTA_TODOS_ARTICULOS,
	 ERROR_EVENTO_CONSULTA_TODOS_ARTICULOS,
	 EVENTO_MODIFICAR_ARTICULO,
	 ERROR_EVENTO_MODIFICAR_ARTICULO,
	 EVENTO_CONSULTAR_ARTICULO_MODIFICAR,
	 ERROR_EVENTO_CONSULTAR_ARTICULO_MODIFICAR,
	
	 
	 EVENTO_ALTA_DEPARTAMENTO,
	 ERROR_EVENTO_ALTA_DEPARTAMENTO,
	 EVENTO_CONSULTA_DEPARTAMENTO,
	 ERROR_EVENTO_CONSULTA_DEPARTAMENTO,
	 EVENTO_CONSULTA_TODOS_DEPARMENTOS,
	 ERROR_EVENTO_CONSULTA_TODOS_DEPARMENTOS,
	 EVENTO_BAJA_DEPARTAMENTO,
	 ERROR_EVENTO_BAJA_DEPARTAMENTO,
	 EVENTO_CONSULTA_DEPARTAMENTO_BAJA,
	 ERROR_EVENTO_CONSULTA_DEPARTAMENTO_BAJA,
	 EVENTO_CONSULTA_DEPARTAMENTO_MODIFICAR,
	 ERROR_EVENTO_CONSULTA_DEPARTAMENTO_MODIFICAR,
	 EVENTO_MODIFICAR_DEPARTAMENTO,
	 ERROR_EVENTO_MODIFICAR_DEPARTAMENTO,
	 
	 
	 
	 EVENTO_ALTA_CONTRATO,
	 ERROR_EVENTO_ALTA_CONTRATO,
	 EVENTO_CONSULTA_CONTRATO,
	 ERROR_EVENTO_CONSULTA_CONTRATO,
	 EVENTO_CONSULTA_TODOS_CONTRATO,
	 ERROR_EVENTO_CONSULTA_TODOS_CONTRATO,
	 EVENTO_CONSULTA_MODIFICAR_CONTRATO,
	 ERROR_EVENTO_CONSULTA_MODIFICAR_CONTRATO,
	 EVENTO_MODIFICAR_CONTRATO,
	 ERROR_EVENTO_MODIFICAR_CONTRATO,
	 
	 EVENTO_VENDER,
	 ERROR_EVENTO_VENDER,
	 
	 EVENTO_ALTA_LINEA_VENTA,
     ERROR_EVENTO_ALTA_LINEA_VENTA,
	 
	 EVENTO_DEVOLUCION,
	 ERROR_EVENTO_DEVOLUCION,
	 
	 EVENTO_CONSULTA_VENTA,
	 ERROR_EVENTO_CONSULTA_VENTA,
	 
	 EVENTO_CONSULTA_TODOS_VENTA,
	 ERROR_EVENTO_CONSULTA_TODOS_VENTA,
	 
	 EVENTO_BALANCE,
	 ERROR_EVENTO_BALANCE,
	 
	 EVENTO_CONSULTA_VENTA_VENDER,
	 ERROR_EVENTO_CONSULTA_VENTA_VENDER
}
