package presentacion.venta.paneles;

import java.sql.Date;
import java.util.List;

import integracion.transacciones.conexion.ExcepcionSQL;

import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

import negocio.contrato.TransferContrato;
import negocio.lineaVenta.TransferLineaVenta;
import negocio.venta.TransferVenta;
import presentacion.articulo.paneles.*;
import presentacion.cliente.paneles.*;
import presentacion.comando.IDEventos;
import presentacion.controlador.Controlador;

/**
 *
 * @author ReplacedKevin
 */
public class PanelVenta extends javax.swing.JPanel {

    /**
     * Creates new form PanelAltaCliente
     */
    public PanelVenta() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelVenta = new javax.swing.JTabbedPane();
        venta = new javax.swing.JPanel();
        etiqFechaV = new javax.swing.JLabel();
        enviarV = new javax.swing.JButton();
        fechaV = new javax.swing.JFormattedTextField();
        idClienteV = new javax.swing.JTextField();
        etiqIDV = new javax.swing.JLabel();
        lineaB1 = new javax.swing.JSeparator();
        lineaB2 = new javax.swing.JSeparator();
        idArticuloV = new javax.swing.JTextField();
        etiqArticuloV = new javax.swing.JLabel();
        costeV = new javax.swing.JTextField();
        etiqCosteV = new javax.swing.JLabel();
        cantidadV = new javax.swing.JSpinner();
        etiqCantidadV = new javax.swing.JLabel();
        anadirV = new javax.swing.JButton();
        etiqCosteTotalV = new javax.swing.JLabel();
        costetotalV = new javax.swing.JTextField();
        nuevaV = new javax.swing.JButton();
        devolucion = new javax.swing.JPanel();
        etiqCantidadD = new javax.swing.JLabel();
        enviarD = new javax.swing.JButton();
        cantidadD = new javax.swing.JSpinner();
        idVentaD = new javax.swing.JTextField();
        etiqIDV1 = new javax.swing.JLabel();
        etiqArticuloV1 = new javax.swing.JLabel();
        idArticuloD = new javax.swing.JTextField();
        balance = new javax.swing.JPanel();
        etiqBalance = new javax.swing.JLabel();
        balancetotal = new javax.swing.JTextField();
        enviarB = new javax.swing.JButton();
        consultaVenta = new javax.swing.JPanel();
        idClienteC = new javax.swing.JTextField();
        enviarC = new javax.swing.JButton();
        etiqApellidosC = new javax.swing.JLabel();
        idArticuloC = new javax.swing.JTextField();
        etiqNombreC = new javax.swing.JLabel();
        etiqIDC = new javax.swing.JLabel();
        idVentaC = new javax.swing.JTextField();
        lineaB3 = new javax.swing.JSeparator();
        costetotalC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        etiqFechaC = new javax.swing.JLabel();
        fechaC = new javax.swing.JFormattedTextField();
        consultaNVenta = new javax.swing.JPanel();
        scrollConsultaN = new javax.swing.JScrollPane();
        etiqIDVentaCN = new javax.swing.JLabel();
        etiqIDClienteCN = new javax.swing.JLabel();
        etiqCosteCN = new javax.swing.JLabel();
        etiqFechaCN = new javax.swing.JLabel();
        enviarCN = new javax.swing.JButton();
        idClienteV = new javax.swing.JTextField();
        etiqIDCV = new javax.swing.JLabel();
        idVentaV = new javax.swing.JTextField();
        etiqIDV = new javax.swing.JLabel();
        aux=0;
        list = new JList<TransferVenta>();
        scrollConsultaN = new javax.swing.JScrollPane(list);
        
        
        etiqFechaV.setText("Fecha:");

        enviarV.setText("Nueva Venta");
        enviarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarVActionPerformed(evt);
            }
        });

        fechaV.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fechaV.setToolTipText("");
        

        etiqIDV.setText("ID_Venta:");

        lineaB1.setBackground(new java.awt.Color(0, 0, 0));

        lineaB2.setBackground(new java.awt.Color(0, 0, 0));

        idArticuloV.setEditable(false);

        etiqArticuloV.setText("ID_Articulo:");

        costeV.setEditable(false);
        

        etiqCosteV.setText("Coste:");

        cantidadV.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        cantidadV.setEditor(new javax.swing.JSpinner.NumberEditor(cantidadV, ""));
        cantidadV.setEnabled(false);

        etiqCantidadV.setText("Cantidad:");

        anadirV.setText("Añadir");
        anadirV.setEnabled(false);
        anadirV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	anadirVActionPerformed(evt);
            }
        });

        etiqCosteTotalV.setText("El coste total es:");

        costetotalV.setEditable(false);
        

        nuevaV.setText("Finalizar");
        nuevaV.setEnabled(false);
        nuevaV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaVActionPerformed(evt);
            }
        });

        etiqIDCV.setText("ID_Cliente:");

        javax.swing.GroupLayout ventaLayout = new javax.swing.GroupLayout(venta);
        venta.setLayout(ventaLayout);
        ventaLayout.setHorizontalGroup(
            ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineaB2)
                .addContainerGap())
            .addGroup(ventaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqArticuloV)
                    .addComponent(etiqCantidadV))
                .addGap(26, 26, 26)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idArticuloV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventaLayout.createSequentialGroup()
                        .addComponent(etiqCosteV)
                        .addGap(18, 18, 18)
                        .addComponent(costeV, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(anadirV))
                .addGap(78, 78, 78))
            .addGroup(ventaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(etiqCosteTotalV)
                .addGap(18, 18, 18)
                .addComponent(costetotalV, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nuevaV)
                .addGap(120, 120, 120))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineaB1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventaLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqIDV)
                    .addComponent(etiqIDCV))
                .addGap(18, 18, 18)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventaLayout.createSequentialGroup()
                        .addComponent(idVentaV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(enviarV))
                    .addGroup(ventaLayout.createSequentialGroup()
                        .addComponent(idClienteV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(etiqFechaV)
                        .addGap(18, 18, 18)
                        .addComponent(fechaV, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
        );
        ventaLayout.setVerticalGroup(
            ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventaLayout.createSequentialGroup()
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventaLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiqFechaV)))
                    .addGroup(ventaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiqIDCV)
                            .addComponent(idClienteV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enviarV)
                    .addComponent(idVentaV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqIDV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lineaB2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idArticuloV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqArticuloV)
                    .addComponent(costeV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqCosteV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anadirV)
                    .addComponent(etiqCantidadV)
                    .addComponent(cantidadV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(lineaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ventaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqCosteTotalV)
                    .addComponent(costetotalV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevaV))
                .addGap(27, 27, 27))
        );

        panelVenta.addTab("Venta", venta);


        etiqCantidadD.setText("Cantidad:");

        enviarD.setText("Devolver");
        enviarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarDActionPerformed(evt);
            }
        });

        cantidadD.setEditor(new javax.swing.JSpinner.NumberEditor(cantidadD, ""));

        etiqIDV1.setText("ID_Venta:");

        etiqArticuloV1.setText("ID_Articulo:");

        idArticuloD.setEditable(true);

        javax.swing.GroupLayout devolucionLayout = new javax.swing.GroupLayout(devolucion);
        devolucion.setLayout(devolucionLayout);
        devolucionLayout.setHorizontalGroup(
            devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, devolucionLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(etiqCantidadD)
                .addGap(29, 29, 29)
                .addComponent(cantidadD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addGroup(devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enviarD)
                    .addGroup(devolucionLayout.createSequentialGroup()
                        .addComponent(etiqArticuloV1)
                        .addGap(18, 18, 18)
                        .addComponent(idArticuloD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
            .addGroup(devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(devolucionLayout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(etiqIDV1)
                    .addGap(18, 18, 18)
                    .addComponent(idVentaD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );
        devolucionLayout.setVerticalGroup(
            devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(devolucionLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqArticuloV1)
                    .addComponent(idArticuloD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidadD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqCantidadD)
                    .addComponent(enviarD))
                .addContainerGap(252, Short.MAX_VALUE))
            .addGroup(devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(devolucionLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(devolucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idVentaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqIDV1))
                    .addContainerGap(313, Short.MAX_VALUE)))
        );

        panelVenta.addTab("Devolucion", devolucion);

        etiqBalance.setText("El balance es:");

        balancetotal.setEditable(false);
        

        enviarB.setText("Balance");
        enviarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	enviarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balanceLayout = new javax.swing.GroupLayout(balance);
        balance.setLayout(balanceLayout);
        balanceLayout.setHorizontalGroup(
            balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(etiqBalance)
                .addGap(18, 18, 18)
                .addComponent(balancetotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114)
                .addComponent(enviarB)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        balanceLayout.setVerticalGroup(
            balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(balanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqBalance)
                    .addComponent(balancetotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarB))
                .addContainerGap(237, Short.MAX_VALUE))
        );

        panelVenta.addTab("Balance", balance);

        idClienteC.setEditable(false);
        

        enviarC.setText("Buscar");
        enviarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCActionPerformed(evt);
            }
        });

        etiqApellidosC.setText("ID_Articulo:");

        idArticuloC.setEditable(false);

        etiqNombreC.setText("ID_Cliente:");

        etiqIDC.setText("ID_Venta:");

        lineaB3.setBackground(new java.awt.Color(0, 0, 0));

        costetotalC.setEditable(false);
        

        jLabel1.setText("Coste:");

        etiqFechaC.setText("Fecha:");

        fechaC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fechaC.setToolTipText("");
        

        javax.swing.GroupLayout consultaVentaLayout = new javax.swing.GroupLayout(consultaVenta);
        consultaVenta.setLayout(consultaVentaLayout);
        consultaVentaLayout.setHorizontalGroup(
            consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaVentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarC)
                .addGap(258, 258, 258))
            .addGroup(consultaVentaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(costetotalC, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addComponent(etiqFechaC)
                .addGap(18, 18, 18)
                .addComponent(fechaC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultaVentaLayout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(consultaVentaLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(etiqNombreC)
                                .addComponent(etiqIDC))
                            .addGap(18, 18, 18)
                            .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idClienteC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(idVentaC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(etiqApellidosC)
                            .addGap(18, 18, 18)
                            .addComponent(idArticuloC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75))
                        .addComponent(lineaB3))
                    .addGap(24, 24, 24)))
        );
        consultaVentaLayout.setVerticalGroup(
            consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaVentaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(enviarC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costetotalC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqFechaC)))
                .addGap(77, 77, 77))
            .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultaVentaLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqIDC)
                        .addComponent(idVentaC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addComponent(lineaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                    .addGroup(consultaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idClienteC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqNombreC)
                        .addComponent(etiqApellidosC)
                        .addComponent(idArticuloC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(154, 154, 154)))
        );

        panelVenta.addTab("Consulta (1)", consultaVenta);

        etiqIDVentaCN.setText("ID_Venta");

        etiqIDClienteCN.setText("ID_Cliente");

        etiqCosteCN.setText("Coste");

        etiqFechaCN.setText("Fecha");

        enviarCN.setText("Enviar");
        enviarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaNVentaLayout = new javax.swing.GroupLayout(consultaNVenta);
        consultaNVenta.setLayout(consultaNVentaLayout);
        consultaNVentaLayout.setHorizontalGroup(
            consultaNVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaNVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqIDVentaCN)
                .addGap(37, 37, 37)
                .addComponent(etiqIDClienteCN)
                .addGap(53, 53, 53)
                .addComponent(etiqCosteCN)
                .addGap(50, 50, 50)
                .addComponent(etiqFechaCN)
                .addContainerGap(282, Short.MAX_VALUE))
            .addComponent(scrollConsultaN)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaNVentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(enviarCN)
                .addGap(267, 267, 267))
        );
        consultaNVentaLayout.setVerticalGroup(
            consultaNVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaNVentaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(consultaNVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDVentaCN)
                    .addComponent(etiqIDClienteCN)
                    .addComponent(etiqCosteCN)
                    .addComponent(etiqFechaCN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollConsultaN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(enviarCN)
                .addGap(7, 7, 7))
        );

        panelVenta.addTab("Consulta (N)", consultaNVenta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVenta)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelVenta)
        );
    }// </editor-fold>                       
    
    //////////////// ALTA VENTA //////////////////// 
    private void enviarVActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	
    	TransferVenta venta = new TransferVenta(); 
        
    	if ( !idClienteV.getText().equals("")
    		 &&!fechaV.getText().equals("")){
    		 
    		String fecha[] = fechaV.getText().split("/");
    		java.sql.Date fechaVenta= new java.sql.Date(0);
    		fechaVenta.setDate(Integer.valueOf(fecha[0]));
    		fechaVenta.setMonth(Integer.valueOf(fecha[1]));
    		fechaVenta.setYear(Integer.valueOf(fecha[2]));
    		
    		idVenta = Integer.valueOf(idVentaV.getText());
    		venta.setIDCliente(Integer.valueOf(idClienteV.getText()));
    		venta.setFecha(fechaVenta);
    		venta.setID(Integer.valueOf(idVentaV.getText()));
    		
    		
    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_VENDER, venta);
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    	
    } 
    
    private void anadirVActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
    	TransferLineaVenta lineaventa = new TransferLineaVenta(); 
        
    	if ( !idArticuloV.getText().equals("")
    		 &&!costeV.getText().equals("")
    		 &&cantidadV.getValue()!=aux){
    		 
    		
    		lineaventa.setIDVenta(idVenta);
    		lineaventa.setIDArticulo(Integer.valueOf(idArticuloV.getText()));
    		lineaventa.setCoste(Float.parseFloat(costeV.getText()));
    		lineaventa.setCantidad((int)cantidadV.getValue());
    		
    		
    		
    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_ALTA_LINEA_VENTA, lineaventa);
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    	
    }  
    
    
    private void nuevaVActionPerformed(java.awt.event.ActionEvent evt) {
    	
    		
    	idClienteV.setText("");
    	idClienteV.setEditable(true);
		
    	fechaV.setText("");
    	fechaV.setEditable(false);
    	idArticuloV.setText("");
    	idArticuloV.setEditable(false);
    	costeV.setText("");
    	costeV.setEditable(false);
    	cantidadV.setValue(0);
    	cantidadV.setEnabled(true);
    	
    	
		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_VENTA_VENDER, idVenta);
   
    }
    
    
    ////////////// DEVOLUCION //////////////////////
    private void enviarDActionPerformed(java.awt.event.ActionEvent evt) {                                        
    		TransferLineaVenta lineaventa = new TransferLineaVenta();
    		
    		if ( !idVentaD.getText().equals("")
    	    	  &&!idArticuloD.getText().equals("")
    	    	  &&cantidadD.getValue()!=aux){
    			
    			lineaventa.setIDVenta(Integer.parseInt(idVentaD.getText()));
    			lineaventa.setIDArticulo(Integer.parseInt(idArticuloD.getText()));
    			lineaventa.setCantidad((int)cantidadD.getValue());
    			Controlador.getInstance().handleRequest(IDEventos.EVENTO_DEVOLUCION, lineaventa);
    			
    		}
    		else
        	{
        		JFrame frame = new JFrame();
        		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
        	}	
    }                                       
    
    
    ////////////////// BALANCE ////////////////////////
    private void enviarBActionPerformed(java.awt.event.ActionEvent evt) { 
    	Controlador.getInstance().handleRequest(IDEventos.EVENTO_BALANCE, null);	
    }                                            

    
    //////////////// CONSULTA /////////////////////////
    private void enviarCActionPerformed(java.awt.event.ActionEvent evt) {                                         
      
    	String id= idVentaC.getText();
    	
    	if ( !id.equals("") ) {
    		
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_VENTA, Integer.valueOf(id));
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    	
    }                                        

    
    
    ////////////////CONSULTA N/////////////////////////
    private void enviarCNActionPerformed(java.awt.event.ActionEvent evt){
		
		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_TODOS_VENTA, null);
    }
    
    
    
    
    
    public void actualizarVentanaVenta(IDEventos idEvento, Object datos) {
    
		if ( IDEventos.EVENTO_VENDER == idEvento ) {
			
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
					idVentaV.setText("");
					idVentaV.setEditable(true);
					idClienteV.setText(""); 
					idClienteV.setEditable(false);
					fechaV.setText("");
					fechaV.setEditable(false);
					nuevaV.setEnabled(false);
					
			    	idArticuloV.setEditable(true);
			    	costeV.setEditable(true);
			    	cantidadV.setEnabled(true);
			    	anadirV.setEnabled(true);
					
					
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Venta creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al crear la venta", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.EVENTO_ALTA_LINEA_VENTA == idEvento ) {
			
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
					idArticuloV.setText(""); 
					costeV.setText("");
					cantidadV.setValue(0);
					nuevaV.setEnabled(true);
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Producto insertado en la venta", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al insertar el producto en la venta", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.EVENTO_CONSULTA_VENTA_VENDER == idEvento ) {
			
			if(datos instanceof TransferVenta)
			{
			
				TransferVenta venta = (TransferVenta) datos;
				
				if (venta!=null) {
				
					costetotalV.setText(venta.getCosteTotal().toString()); 
					nuevaV.setEnabled(false);
					idVenta=null;
					enviarV.setEnabled(true);
				}
				else 
				{
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al consultar el coste total de la venta", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.ERROR_EVENTO_VENDER == idEvento || IDEventos.ERROR_EVENTO_ALTA_LINEA_VENTA == idEvento || IDEventos.ERROR_EVENTO_CONSULTA_VENTA_VENDER== idEvento) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		
		
	}                                     

    public void actualizarVentanaDevolucion(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_DEVOLUCION == idEvento ) {
			
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {

					idVentaD.setText(""); 
					idArticuloD.setText(""); 
					cantidadD.setValue(0);
					
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Articulo devuelto", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al devolver el articulo", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.ERROR_EVENTO_DEVOLUCION == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		
		
	}

    public void actualizarVentanaBalance(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_BALANCE == idEvento ) {
			
			if(datos instanceof Float)
			{
				Float valor = (Float) datos;
				
				if (valor!=-1) {
					
					balancetotal.setText(valor.toString()); 
					
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error en el balance", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.ERROR_EVENTO_BALANCE == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		
		
	}
    
    public void actualizarVentanaConsulta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_CONSULTA_VENTA == idEvento ) {
					
			if ( datos instanceof TransferVenta) {
				
				TransferVenta venta = (TransferVenta) datos;
				
				if (venta != null) {
					
					String fecha=""; 
					java.sql.Date fechainicio = venta.getFecha();
					fecha+= fechainicio.getDay();
					fecha+="/";
					fecha+= fechainicio.getMonth();
					fecha+="/";
					fecha+= fechainicio.getYear();
					
					idClienteC.setText(venta.getIDCliente().toString());
					idArticuloC.setText(venta.getID().toString());
					costetotalC.setText(venta.getCosteTotal().toString());
					fechaC.setText(fecha);
				}
					
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar la venta", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		else if ( IDEventos.ERROR_EVENTO_CONSULTA_VENTA == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
	}	

    public void actualizarVentanaConsultaN(IDEventos idEvento, Object datos) {

    	if ( IDEventos.EVENTO_CONSULTA_TODOS_VENTA == idEvento ) {

    		if ( datos instanceof List) {

    			@SuppressWarnings("unchecked")
    			List<TransferVenta> listaVentas = (List<TransferVenta>) datos;

    			TransferVenta[] ventas = new TransferVenta[listaVentas.size()];
    			listaVentas.toArray(ventas);
    			
    			list.setListData(ventas);
    			//Como ponerlo aqui?
    		}
    		else {
    			JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar todos las ventas", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	} 
    	else if ( IDEventos.ERROR_EVENTO_CONSULTA_TODOS_VENTA== idEvento ) {

    		if ( datos instanceof ExcepcionSQL ) {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		else {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }
    
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton anadirV;
    private javax.swing.JPanel balance;
    private javax.swing.JTextField balancetotal;
    private javax.swing.JSpinner cantidadD;
    private javax.swing.JSpinner cantidadV;
    private javax.swing.JPanel consultaNVenta;
    private javax.swing.JPanel consultaVenta;
    private javax.swing.JTextField costeV;
    private javax.swing.JTextField costetotalC;
    private javax.swing.JTextField costetotalV;
    private javax.swing.JPanel devolucion;
    private javax.swing.JButton enviarB;
    private javax.swing.JButton enviarC;
    private javax.swing.JButton enviarCN;
    private javax.swing.JButton enviarD;
    private javax.swing.JButton enviarV;
    private javax.swing.JLabel etiqApellidosC;
    private javax.swing.JLabel etiqArticuloV;
    private javax.swing.JLabel etiqArticuloV1;
    private javax.swing.JLabel etiqBalance;
    private javax.swing.JLabel etiqCantidadD;
    private javax.swing.JLabel etiqCantidadV;
    private javax.swing.JLabel etiqCosteCN;
    private javax.swing.JLabel etiqCosteTotalV;
    private javax.swing.JLabel etiqCosteV;
    private javax.swing.JLabel etiqFechaC;
    private javax.swing.JLabel etiqFechaCN;
    private javax.swing.JLabel etiqFechaV;
    private javax.swing.JLabel etiqIDC;
    private javax.swing.JLabel etiqIDClienteCN;
    private javax.swing.JLabel etiqIDV;
    private javax.swing.JLabel etiqIDV1;
    private javax.swing.JLabel etiqIDVentaCN;
    private javax.swing.JLabel etiqNombreC;
    private javax.swing.JFormattedTextField fechaV;
    private javax.swing.JFormattedTextField fechaC;
    private javax.swing.JTextField idArticuloC;
    private javax.swing.JTextField idArticuloD;
    private javax.swing.JTextField idArticuloV;
    private javax.swing.JTextField idVentaC;
    private javax.swing.JTextField idClienteC;
    private javax.swing.JTextField idVentaD;
    private javax.swing.JTextField idClienteV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator lineaB1;
    private javax.swing.JSeparator lineaB2;
    private javax.swing.JSeparator lineaB3;
    private javax.swing.JButton nuevaV;
    private javax.swing.JTabbedPane panelVenta;
    private javax.swing.JScrollPane scrollConsultaN;
    private javax.swing.JPanel venta;
    private javax.swing.JLabel etiqIDCV;
    private javax.swing.JTextField idVentaV;
    private JList<TransferVenta> list;
    private Integer idVenta;
    private Integer aux;
    // End of variables declaration                        
    
          
}
