/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.cliente.paneles;


import integracion.transacciones.conexion.ExcepcionSQL;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import negocio.cliente.TransferCliente;
import presentacion.comando.IDEventos;
import presentacion.controlador.Controlador;

/**
 *
 * @author ReplacedKevin
 */
public class PanelCliente extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form PanelAltaCliente
     */
    public PanelCliente() {
        initComponents();
        botones();
        valor="Socio";
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {


        panelCliente = new javax.swing.JTabbedPane();
        altaCliente = new javax.swing.JPanel();
        nombreA = new javax.swing.JTextField();
        dniA = new javax.swing.JTextField();
        etiqDNIA = new javax.swing.JLabel();
        enviarA = new javax.swing.JButton();
        tipoA = new javax.swing.JComboBox();
        etiqEmailA = new javax.swing.JLabel();
        etiqApellidosA = new javax.swing.JLabel();
        apellidosA = new javax.swing.JTextField();
        etiqTelefonoA = new javax.swing.JLabel();
        emailA = new javax.swing.JTextField();
        telefonoA = new javax.swing.JTextField();
        etiqNombreA = new javax.swing.JLabel();
        intencionA = new javax.swing.JCheckBox();
        bajaCliente = new javax.swing.JPanel();
        nombreB = new javax.swing.JTextField();
        dniB = new javax.swing.JTextField();
        etiqDNIB = new javax.swing.JLabel();
        enviarB = new javax.swing.JButton();
        etiqEmailAc1 = new javax.swing.JLabel();
        etiqApellidosB = new javax.swing.JLabel();
        apellidosB = new javax.swing.JTextField();
        etiqTelefonoB = new javax.swing.JLabel();
        emailB = new javax.swing.JTextField();
        telefonoB = new javax.swing.JTextField();
        etiqNombreB = new javax.swing.JLabel();
        etiqIDB = new javax.swing.JLabel();
        idBuscarClienteB = new javax.swing.JTextField();
        borraB = new javax.swing.JButton();
        lineaB = new javax.swing.JSeparator();
        actualizaCliente = new javax.swing.JPanel();
        nombreAc = new javax.swing.JTextField();
        dniAc = new javax.swing.JTextField();
        etiqDNIAc = new javax.swing.JLabel();
        enviarAc = new javax.swing.JButton();
        etiqEmailAc = new javax.swing.JLabel();
        etiqApellidosAc = new javax.swing.JLabel();
        apellidosAc = new javax.swing.JTextField();
        etiqTelefonoAc = new javax.swing.JLabel();
        emailAc = new javax.swing.JTextField();
        telefonoAc = new javax.swing.JTextField();
        etiqNombreAc = new javax.swing.JLabel();
        etiqIDAc = new javax.swing.JLabel();
        idBuscarClienteAc = new javax.swing.JTextField();
        nuevaAc = new javax.swing.JButton();
        actualizaAc = new javax.swing.JButton();
        lineaAc = new javax.swing.JSeparator();
        consultaCliente = new javax.swing.JPanel();
        nombreC = new javax.swing.JTextField();
        dniC = new javax.swing.JTextField();
        etiqDNIC = new javax.swing.JLabel();
        enviarC = new javax.swing.JButton();
        etiqEmailC = new javax.swing.JLabel();
        etiqApellidosC = new javax.swing.JLabel();
        apellidosC = new javax.swing.JTextField();
        etiqTelefonoC = new javax.swing.JLabel();
        emailC = new javax.swing.JTextField();
        telefonoC = new javax.swing.JTextField();
        etiqNombreC = new javax.swing.JLabel();
        etiqIDC = new javax.swing.JLabel();
        idBuscarClienteC = new javax.swing.JTextField();
        lineaB1 = new javax.swing.JSeparator();
        intencionC = new javax.swing.JCheckBox();
        tiposocioC = new javax.swing.JCheckBox();
        consultaClienteN = new javax.swing.JPanel();
        etiqIDCN = new javax.swing.JLabel();
        etiqNombreCN = new javax.swing.JLabel();
        etiqApellidosCN = new javax.swing.JLabel();
        etiqEmailCN = new javax.swing.JLabel();
        etiqTelefonoCN = new javax.swing.JLabel();
        etiqIntencionCN = new javax.swing.JLabel();
        etiqTipoCN = new javax.swing.JLabel();
        enviarCN = new javax.swing.JButton();
        list = new JList<TransferCliente>();
        scrollConsultaN = new javax.swing.JScrollPane(list);

        etiqDNIA.setText("DNI:");

        enviarA.setText("Enviar");
        enviarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAActionPerformed(evt);
            }
        });

        tipoA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Socio", "No Socio" }));
        tipoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAActionPerformed(evt);
            }
        });

        etiqEmailA.setText("Email:");

        etiqApellidosA.setText("Apellidos:");

        etiqTelefonoA.setText("Telefono:");

        etiqNombreA.setText("Nombre:");

        intencionA.setText("Intencion");

        javax.swing.GroupLayout altaClienteLayout = new javax.swing.GroupLayout(altaCliente);
        altaCliente.setLayout(altaClienteLayout);
        altaClienteLayout.setHorizontalGroup(
            altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(altaClienteLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(altaClienteLayout.createSequentialGroup()
                            .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(altaClienteLayout.createSequentialGroup()
                                    .addComponent(etiqTelefonoA)
                                    .addGap(18, 18, 18)
                                    .addComponent(telefonoA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(altaClienteLayout.createSequentialGroup()
                                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(etiqDNIA)
                                        .addComponent(etiqNombreA))
                                    .addGap(23, 23, 23)
                                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(dniA, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(174, 174, 174)
                            .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(intencionA)
                                .addGroup(altaClienteLayout.createSequentialGroup()
                                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(etiqEmailA)
                                        .addComponent(etiqApellidosA, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(24, 24, 24)
                                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(apellidosA, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(emailA)))))
                        .addGroup(altaClienteLayout.createSequentialGroup()
                            .addGap(179, 179, 179)
                            .addComponent(tipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(altaClienteLayout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(enviarA)))
                    .addContainerGap(56, Short.MAX_VALUE)))
        );
        altaClienteLayout.setVerticalGroup(
            altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 412, Short.MAX_VALUE)
            .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(altaClienteLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(tipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqNombreA)
                        .addComponent(nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(apellidosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqApellidosA))
                    .addGap(31, 31, 31)
                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqEmailA)
                        .addComponent(emailA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqDNIA)
                        .addComponent(dniA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(28, 28, 28)
                    .addGroup(altaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqTelefonoA)
                        .addComponent(telefonoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(intencionA))
                    .addGap(18, 18, 18)
                    .addComponent(enviarA)
                    .addContainerGap(163, Short.MAX_VALUE)))
        );

        panelCliente.addTab("Alta", altaCliente);

        dniB.setEditable(false);

        etiqDNIB.setText("DNI:");

        enviarB.setText("Buscar");
        enviarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBActionPerformed(evt);
            }
        });

        etiqEmailAc1.setText("Email:");

        etiqApellidosB.setText("Apellidos:");

        apellidosB.setEditable(false);

        etiqTelefonoB.setText("Telefono:");

        emailB.setEditable(false);

        telefonoB.setEditable(false);

        etiqNombreB.setText("Nombre:");

        etiqIDB.setText("ID:");

        borraB.setText("Borrar");
        borraB.setEnabled(false);
        borraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraBActionPerformed(evt);
            }
        });

        lineaB.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout bajaClienteLayout = new javax.swing.GroupLayout(bajaCliente);
        bajaCliente.setLayout(bajaClienteLayout);
        bajaClienteLayout.setHorizontalGroup(
            bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqTelefonoB)
                    .addComponent(etiqDNIB)
                    .addComponent(etiqNombreB)
                    .addComponent(etiqIDB))
                .addGap(18, 18, 18)
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreB)
                    .addComponent(telefonoB, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(dniB)
                    .addComponent(idBuscarClienteB))
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bajaClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                        .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqApellidosB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiqEmailAc1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(borraB)))
                    .addGroup(bajaClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(enviarB)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(28, 28, 28))
            .addGroup(bajaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineaB)
                .addContainerGap())
        );
        bajaClienteLayout.setVerticalGroup(
            bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bajaClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDB)
                    .addComponent(idBuscarClienteB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarB))
                .addGap(23, 23, 23)
                .addComponent(lineaB, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreB)
                    .addComponent(etiqApellidosB)
                    .addComponent(apellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDNIB)
                    .addComponent(etiqEmailAc1)
                    .addComponent(emailB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(bajaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqTelefonoB)
                    .addComponent(telefonoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borraB))
                .addGap(113, 113, 113))
        );

        panelCliente.addTab("Baja", bajaCliente);

        dniAc.setEditable(false);

        etiqDNIAc.setText("DNI:");

        enviarAc.setText("Buscar");
        enviarAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAcActionPerformed(evt);
            }
        });

        etiqEmailAc.setText("Email:");

        etiqApellidosAc.setText("Apellidos:");

        apellidosAc.setEditable(false);

        etiqTelefonoAc.setText("Telefono:");

        emailAc.setEditable(false);

        telefonoAc.setEditable(false);

        etiqNombreAc.setText("Nombre:");

        etiqIDAc.setText("ID:");

        nuevaAc.setText("Nueva Busqueda");
        nuevaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaAcActionPerformed(evt);
            }
        });

        actualizaAc.setText("Actualizar");
        actualizaAc.setEnabled(false);
        actualizaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaAcActionPerformed(evt);
            }
        });

        lineaAc.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout actualizaClienteLayout = new javax.swing.GroupLayout(actualizaCliente);
        actualizaCliente.setLayout(actualizaClienteLayout);
        actualizaClienteLayout.setHorizontalGroup(
            actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizaClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqTelefonoAc)
                    .addComponent(etiqDNIAc)
                    .addComponent(etiqNombreAc)
                    .addComponent(etiqIDAc))
                .addGap(18, 18, 18)
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreAc)
                    .addComponent(telefonoAc, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(dniAc)
                    .addComponent(idBuscarClienteAc))
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizaClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etiqApellidosAc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etiqEmailAc, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailAc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosAc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(actualizaAc)))
                    .addGroup(actualizaClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(enviarAc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(nuevaAc)))
                .addGap(28, 28, 28))
            .addComponent(lineaAc)
        );
        actualizaClienteLayout.setVerticalGroup(
            actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizaClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDAc)
                    .addComponent(idBuscarClienteAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarAc)
                    .addComponent(nuevaAc))
                .addGap(30, 30, 30)
                .addComponent(lineaAc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreAc)
                    .addComponent(etiqApellidosAc)
                    .addComponent(apellidosAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDNIAc)
                    .addComponent(etiqEmailAc)
                    .addComponent(emailAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(actualizaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqTelefonoAc)
                    .addComponent(telefonoAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actualizaAc))
                .addGap(113, 113, 113))
        );

        panelCliente.addTab("Actualiza", actualizaCliente);


        dniC.setEditable(false);

        etiqDNIC.setText("DNI:");

        enviarC.setText("Buscar");
        enviarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCActionPerformed(evt);
            }
        });

        etiqEmailC.setText("Email:");

        etiqApellidosC.setText("Apellidos:");

        apellidosC.setEditable(false);

        etiqTelefonoC.setText("Telefono:");

        emailC.setEditable(false);

        telefonoC.setEditable(false);

        etiqNombreC.setText("Nombre:");

        etiqIDC.setText("ID:");

        lineaB1.setBackground(new java.awt.Color(0, 0, 0));

        intencionC.setText("Intencion");
        intencionC.setEnabled(false);

        tiposocioC.setText("Socio");
        tiposocioC.setEnabled(false);

        javax.swing.GroupLayout consultaClienteLayout = new javax.swing.GroupLayout(consultaCliente);
        consultaCliente.setLayout(consultaClienteLayout);
        consultaClienteLayout.setHorizontalGroup(
            consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaClienteLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqTelefonoC)
                    .addComponent(etiqDNIC)
                    .addComponent(etiqNombreC)
                    .addComponent(etiqIDC))
                .addGap(18, 18, 18)
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreC)
                    .addComponent(telefonoC, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(dniC)
                    .addComponent(idBuscarClienteC))
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaClienteLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(enviarC)
                        .addGap(0, 248, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaClienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(consultaClienteLayout.createSequentialGroup()
                                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqApellidosC, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiqEmailC, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidosC, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(consultaClienteLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(intencionC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiposocioC)))))
                .addGap(20, 20, 20))
            .addGroup(consultaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lineaB1)
                .addContainerGap())
        );
        consultaClienteLayout.setVerticalGroup(
            consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDC)
                    .addComponent(idBuscarClienteC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarC))
                .addGap(23, 23, 23)
                .addComponent(lineaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreC)
                    .addComponent(etiqApellidosC)
                    .addComponent(apellidosC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDNIC)
                    .addComponent(etiqEmailC)
                    .addComponent(emailC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(consultaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqTelefonoC)
                    .addComponent(telefonoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(intencionC)
                    .addComponent(tiposocioC))
                .addGap(115, 115, 115))
        );

        panelCliente.addTab("Consulta (1)", consultaCliente);

        etiqIDCN.setText("ID");

        etiqNombreCN.setText("Nombre");

        etiqApellidosCN.setText("Apellidos");

        etiqEmailCN.setText("Email");

        etiqTelefonoCN.setText("Telefono");

        etiqIntencionCN.setText("Intencion");

        etiqTipoCN.setText("Tipo");
        
        
        
        enviarCN.setText("Enviar");
        enviarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCNActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout consultaClienteNLayout = new javax.swing.GroupLayout(consultaClienteN);
        consultaClienteN.setLayout(consultaClienteNLayout);
        consultaClienteNLayout.setHorizontalGroup(
            consultaClienteNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaClienteNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqIDCN)
                .addGap(37, 37, 37)
                .addComponent(etiqNombreCN)
                .addGap(53, 53, 53)
                .addComponent(etiqApellidosCN)
                .addGap(50, 50, 50)
                .addComponent(etiqEmailCN)
                .addGap(53, 53, 53)
                .addComponent(etiqTelefonoCN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(etiqIntencionCN)
                .addGap(26, 26, 26)
                .addComponent(etiqTipoCN)
                .addContainerGap())
            .addComponent(scrollConsultaN)
            .addGroup(consultaClienteNLayout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(enviarCN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaClienteNLayout.setVerticalGroup(
            consultaClienteNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaClienteNLayout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(consultaClienteNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDCN)
                    .addComponent(etiqNombreCN)
                    .addComponent(etiqApellidosCN)
                    .addComponent(etiqEmailCN)
                    .addComponent(etiqTelefonoCN)
                    .addComponent(etiqIntencionCN)
                    .addComponent(etiqTipoCN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollConsultaN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(enviarCN)
                .addContainerGap())
        );

        panelCliente.addTab("Consulta (N)", consultaClienteN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>                         
    
    
    /////////// ALTA CLIENTE ///////////////
    private void enviarAActionPerformed(java.awt.event.ActionEvent evt) {                                        
       
    	TransferCliente cliente = new TransferCliente(); 
    	
    	if(valor.equalsIgnoreCase("Socio"))
    	{
	    	if ( !nombreA.getText().equals("") 
					&& !apellidosA.getText().equals("")
					&& !dniA.getText().equals("") 
					&& !emailA.getText().equals("")
					&& !telefonoA.getText().equals("")){
	    		 
	    		cliente.setNombre(nombreA.getText());
	    		cliente.setApellidos(apellidosA.getText());
	    		cliente.setDNI(dniA.getText());
	    		cliente.setEmail(emailA.getText());
	    		cliente.setTelefono(telefonoA.getText()); 		
	    		cliente.setTipo(true);
	    		
	    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_ALTA_SOCIO, cliente);
	    	}
	    	else
	    	{
	    		JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
	    	}
	    }
    	else
    	{

	    	if ( !nombreA.getText().equals("") 
					&& !apellidosA.getText().equals("")){

	    		cliente.setNombre(nombreA.getText());
	    		cliente.setApellidos(apellidosA.getText());
	    		cliente.setDNI(dniA.getText());
	    		cliente.setIntencion(intencionA.isSelected());
	    		cliente.setTipo(false);
	    		
	    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_ALTA_NO_SOCIO, cliente);
	    	}
	    	else
	    	{
	    		JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
	    	}
    	}
    	
    	
    }                                       

    private void tipoAActionPerformed(java.awt.event.ActionEvent evt) {                                      

        String aux = (String) tipoA.getSelectedItem();
        valor = aux;
        
        if(aux.equalsIgnoreCase("Socio"))
        {
            intencionA.setVisible(false);
            telefonoA.setVisible(true);
            etiqTelefonoA.setVisible(true);
            dniA.setVisible(true);
            etiqDNIA.setVisible(true);
            emailA.setVisible(true);
            etiqEmailA.setVisible(true);
        }
        else
        {
            telefonoA.setVisible(false);
            etiqTelefonoA.setVisible(false);
            dniA.setVisible(false);
            etiqDNIA.setVisible(false);
            emailA.setVisible(false);
            etiqEmailA.setVisible(false);
            intencionA.setVisible(true);

        }

    }                                     

    
    
    ///////////// ACTUALIZAR CLIENTE /////////////
    private void enviarAcActionPerformed(java.awt.event.ActionEvent evt) {   
    	
    	idBuscarClienteAc.setEditable(false);//TextField
		
		String id = idBuscarClienteAc.getText();	
		if ( !id.equals("") ) {
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTAR_CLIENTE_MODIFICAR, Integer.valueOf(id));
		}
		else
		{
			JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
		}

		
    }                                        

    private void nuevaAcActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	idCliente = null;
    	idBuscarClienteAc.setText("");
    	idBuscarClienteAc.setEditable(false);
		
    	nombreAc.setText("");
		nombreAc.setEditable(false);
		apellidosAc.setText("");
		apellidosAc.setEditable(false);
		dniAc.setText("");
		dniAc.setEditable(false);
		emailAc.setText("");
		emailAc.setEditable(false);
		telefonoAc.setText("");
		telefonoAc.setEditable(false);
		//intencionAc.setSelected(false);
		//tiposocioAc.setSelected(false);
		
    }
    
    private void actualizaAcActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	idBuscarClienteAc.setEditable(false);
		
		TransferCliente cliente = new TransferCliente();
		
		if ( idCliente != null 
				&& !nombreAc.getText().equals("")
				&& !apellidosAc.getText().equals("")
				&& !dniAc.getText().equals("") 
				&& !emailAc.getText().equals("")
				&& !telefonoAc.getText().equals("")) {
			
			cliente.setDNI(dniAc.getText());
			cliente.setNombre(nombreAc.getText());
			cliente.setApellidos(apellidosAc.getText());
			cliente.setEmail(emailAc.getText());
			cliente.setTelefono(telefonoAc.getText());
			
			
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_MODIFICAR_CLIENTE, cliente);
			
		}
		else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    }
    
    
    /////////////// BORRAR CLIENTE //////////////////
    private void enviarBActionPerformed(java.awt.event.ActionEvent evt) {                                        
      
    	String id = idBuscarClienteB.getText();

    	if ( !id.equals("") ) {
    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTAR_CLIENTE_BORRAR, Integer.valueOf(id));
    	}
    	else {
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    	
    }                                       
                                    
    private void borraBActionPerformed(java.awt.event.ActionEvent evt){
    	
    	if ( idCliente != null )
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_BAJA_CLIENTE, idCliente);
		else
		{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Error al cargar el cliente", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }
    
    
    /////////////// CONSULTAR CLIENTE ///////////////
    private void enviarCActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	String id= idBuscarClienteC.getText();
    	
    	if ( !id.equals("") ) {
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_CLIENTE, Integer.valueOf(id));
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    }                                       
   
    ////////////// CONSULTAR N CLIENTES ///////////////////
    private void enviarCNActionPerformed(java.awt.event.ActionEvent evt){
    	
		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_TODOS_CLIENTES, null);
    }
  
    
   
    
    public void actualizarVentanaAlta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_ALTA_SOCIO == idEvento ) {
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
		    		nombreA.setText(""); 
					apellidosA.setText(""); 
					dniA.setText(""); 
					emailA.setText(""); 
					telefonoA.setText("");
					
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Socio creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al crear el socio", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.ERROR_ALTA_SOCIO == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		else if ( IDEventos.EVENTO_ALTA_NO_SOCIO == idEvento ) {
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				if (correcto) {
	
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame,"No socio creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
					
					nombreA.setText(""); 
					apellidosA.setText(""); 
					dniA.setText(""); 
					intencionA.setSelected(false);
					valor="Socio";
					
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al crear el no socio", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}

		}
		else if ( IDEventos.ERROR_EVENTO_ALTA_NO_SOCIO == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {

				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		
	}

    public void actualizarVentanaConsulta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_CONSULTA_CLIENTE == idEvento ) {
		
			if ( datos instanceof TransferCliente) {
				
				TransferCliente cliente = (TransferCliente) datos;
				
				if ( cliente != null ) {
					
					nombreC.setText(cliente.getNombre());
					apellidosC.setText(cliente.getApellidos());
					dniC.setText(cliente.getDNI());
					emailC.setText(cliente.getEmail());
					telefonoC.setText(cliente.getTelefono());
					intencionC.setSelected(cliente.getIntencion());
					tiposocioC.setSelected(cliente.getTipo());	
				}
					
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar el cliente", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		else if ( IDEventos.ERROR_CONSULTA_CLIENTE == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
	}
    
    public void actualizarVentanaActualiza(IDEventos idEvento, Object datos){
	    
    	if ( IDEventos.EVENTO_MODIFICAR_CLIENTE == idEvento ) {
			
			if ( datos instanceof Boolean ) {
				
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
					idBuscarClienteAc.setText("");
					idBuscarClienteAc.setEditable(false);
					nombreAc.setText("");
					nombreAc.setEditable(false);
					apellidosAc.setText("");
					apellidosAc.setEditable(false);
					dniAc.setText("");
					dniAc.setEditable(false);
					emailAc.setText("");
					emailAc.setEditable(false);
					telefonoAc.setText("");
					telefonoAc.setEditable(false);
					
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame, "Cliente modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame, "El cliente no se ha modificado", "Error", JOptionPane.ERROR_MESSAGE);
				}
				idCliente = null;
			}
		}
		else if ( IDEventos.EVENTO_CONSULTAR_CLIENTE_MODIFICAR == idEvento ) {
			
			if ( datos instanceof TransferCliente) {
				
				TransferCliente cliente = (TransferCliente) datos;
					
				idCliente = cliente.getID();
				nombreAc.setText(cliente.getNombre());
				nombreAc.setEditable(true);
				apellidosAc.setText(cliente.getApellidos());
				apellidosAc.setEditable(true);
				dniAc.setText(cliente.getDNI());
				dniAc.setEditable(true);
				emailAc.setText(cliente.getEmail());
				emailAc.setEditable(true);
				telefonoAc.setText(cliente.getTelefono());
				telefonoAc.setEditable(true);
				
				
			}
		}
		else if ( IDEventos.ERROR_MODIFICAR_CLIENTE == idEvento || IDEventos.ERROR_EVENTO_CONSULTAR_CLIENTE_MODIFICAR == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
    }

    public void actualizarVentanaBorra(IDEventos idEvento, Object datos){
    	
    	if ( IDEventos.EVENTO_BAJA_CLIENTE == idEvento ) {

    		if ( datos instanceof Boolean ) {

    			Boolean correcto = (Boolean) datos;

    			if (correcto) {
    				
    				idBuscarClienteB.setText("");
    				idCliente = null;
    				dniB.setText("");
    				nombreB.setText("");
    				apellidosB.setText("");
    				telefonoB.setText("");
    				emailB.setText("");
    				borraB.setEnabled(false);

    				JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Cliente borrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    			}
    			else {

    				JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"El cliente no se ha borrado", "Error", JOptionPane.ERROR_MESSAGE);
    			}
    		}
    	}
    	else if (IDEventos.EVENTO_CONSULTAR_CLIENTE_BORRAR == idEvento) {

    		if ( datos instanceof TransferCliente) {

    			TransferCliente cliente = (TransferCliente) datos;

    			idCliente = cliente.getID();
    			nombreB.setText(cliente.getNombre());
				apellidosB.setText(cliente.getApellidos());
				dniB.setText(cliente.getDNI());
				emailB.setText(cliente.getEmail());
				telefonoB.setText(cliente.getTelefono());
    			borraB.setEnabled(true);
    		}
    	}
    	else if ( IDEventos.ERROR_EVENTO_BAJA_CLIENTE == idEvento || IDEventos.ERROR_CONSULTAR_CLIENTE_BORRAR == idEvento ) {

    		if ( datos instanceof ExcepcionSQL ) {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		else {
    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }
    
    public void actualizarVentanaConsultaN(IDEventos idEvento, Object datos) {

    	if ( IDEventos.EVENTO_CONSULTA_TODOS_CLIENTES == idEvento ) {
    		
    		if ( datos instanceof ArrayList) {

    			@SuppressWarnings("unchecked")
    			ArrayList<TransferCliente> listaClientes = (ArrayList<TransferCliente>) datos;

    			TransferCliente[] clientes = new TransferCliente[listaClientes.size()];
    			listaClientes.toArray(clientes);
    			
    			list.setListData(clientes);

    		}
    		else {
    			JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar todos los clientes", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    	else if ( IDEventos.ERROR_EVENTO_CONSULTA_TODOS_CLIENTES == idEvento ) {

    		if ( datos instanceof ExcepcionSQL ) {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		else {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }
    
    
    
    private void botones(){
    	
    	intencionA.setVisible(false);
        telefonoA.setVisible(true);
        etiqTelefonoA.setVisible(true);
        dniA.setVisible(true);
        etiqDNIA.setVisible(true);
        emailA.setVisible(true);
        etiqEmailA.setVisible(true);
    }
 

    // Variables declaration - do not modify                     
    private javax.swing.JButton actualizaAc;
    private javax.swing.JPanel actualizaCliente;
    private javax.swing.JPanel altaCliente;
    private javax.swing.JTextField apellidosA;
    private javax.swing.JTextField apellidosAc;
    private javax.swing.JTextField apellidosB;
    private javax.swing.JTextField apellidosC;
    private javax.swing.JPanel bajaCliente;
    private javax.swing.JButton borraB;
    private javax.swing.JPanel consultaCliente;
    private javax.swing.JPanel consultaClienteN;
    private javax.swing.JTextField dniA;
    private javax.swing.JTextField dniAc;
    private javax.swing.JTextField dniB;
    private javax.swing.JTextField dniC;
    private javax.swing.JTextField emailA;
    private javax.swing.JTextField emailAc;
    private javax.swing.JTextField emailB;
    private javax.swing.JTextField emailC;
    private javax.swing.JButton enviarA;
    private javax.swing.JButton enviarAc;
    private javax.swing.JButton enviarB;
    private javax.swing.JButton enviarC;
    private javax.swing.JButton enviarCN;
    private javax.swing.JLabel etiqApellidosA;
    private javax.swing.JLabel etiqApellidosAc;
    private javax.swing.JLabel etiqApellidosB;
    private javax.swing.JLabel etiqApellidosC;
    private javax.swing.JLabel etiqApellidosCN;
    private javax.swing.JLabel etiqDNIA;
    private javax.swing.JLabel etiqDNIAc;
    private javax.swing.JLabel etiqDNIB;
    private javax.swing.JLabel etiqDNIC;
    private javax.swing.JLabel etiqEmailA;
    private javax.swing.JLabel etiqEmailAc;
    private javax.swing.JLabel etiqEmailAc1;
    private javax.swing.JLabel etiqEmailC;
    private javax.swing.JLabel etiqEmailCN;
    private javax.swing.JLabel etiqIDAc;
    private javax.swing.JLabel etiqIDB;
    private javax.swing.JLabel etiqIDC;
    private javax.swing.JLabel etiqIDCN;
    private javax.swing.JLabel etiqIntencionCN;
    private javax.swing.JLabel etiqNombreA;
    private javax.swing.JLabel etiqNombreAc;
    private javax.swing.JLabel etiqNombreB;
    private javax.swing.JLabel etiqNombreC;
    private javax.swing.JLabel etiqNombreCN;
    private javax.swing.JLabel etiqTelefonoA;
    private javax.swing.JLabel etiqTelefonoAc;
    private javax.swing.JLabel etiqTelefonoB;
    private javax.swing.JLabel etiqTelefonoC;
    private javax.swing.JLabel etiqTelefonoCN;
    private javax.swing.JLabel etiqTipoCN;
    private javax.swing.JTextField idBuscarClienteAc;
    private javax.swing.JTextField idBuscarClienteB;
    private javax.swing.JTextField idBuscarClienteC;
    private javax.swing.JCheckBox intencionA;
    private javax.swing.JCheckBox intencionC;
    private javax.swing.JSeparator lineaAc;
    private javax.swing.JSeparator lineaB;
    private javax.swing.JSeparator lineaB1;
    private javax.swing.JTextField nombreA;
    private javax.swing.JTextField nombreAc;
    private javax.swing.JTextField nombreB;
    private javax.swing.JTextField nombreC;
    private javax.swing.JButton nuevaAc;
    private javax.swing.JTabbedPane panelCliente;
    private javax.swing.JScrollPane scrollConsultaN;
    private javax.swing.JTextField telefonoA;
    private javax.swing.JTextField telefonoAc;
    private javax.swing.JTextField telefonoB;
    private javax.swing.JTextField telefonoC;
    private javax.swing.JComboBox tipoA;
    private javax.swing.JCheckBox tiposocioC; 
    private JList<TransferCliente> list;
    private String valor;
    private Integer idCliente;
   
    
}
