/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.articulo.paneles;

import java.util.ArrayList;
import java.util.List;

import integracion.transacciones.conexion.ExcepcionSQL;

import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

import negocio.articulo.TransferArticulo;
import negocio.cliente.TransferCliente;
import presentacion.cliente.paneles.*;
import presentacion.comando.IDEventos;
import presentacion.controlador.Controlador;

/**
 *
 * @author ReplacedKevin
 */
public class PanelArticulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelAltaCliente
     */
    public PanelArticulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        panelArticulo = new javax.swing.JTabbedPane();
        altaArticulo = new javax.swing.JPanel();
        nombreA = new javax.swing.JTextField();
        etiqCantidadA = new javax.swing.JLabel();
        etiqValorA = new javax.swing.JLabel();
        enviarA = new javax.swing.JButton();
        etiqNombreA = new javax.swing.JLabel();
        cantidadA = new javax.swing.JSpinner();
        valorA = new javax.swing.JTextField();
        actualizaArticulo = new javax.swing.JPanel();
        nombreAc = new javax.swing.JTextField();
        enviarAc = new javax.swing.JButton();
        etiqNombreAc = new javax.swing.JLabel();
        etiqIDAc = new javax.swing.JLabel();
        idArticuloBuscarAc = new javax.swing.JTextField();
        nuevaAc = new javax.swing.JButton();
        actualizaAc = new javax.swing.JButton();
        lineaAc = new javax.swing.JSeparator();
        etiqValorAc = new javax.swing.JLabel();
        etiqCantidadAc = new javax.swing.JLabel();
        cantidadAc = new javax.swing.JSpinner();
        valorAc = new javax.swing.JTextField();
        consultaArticulo = new javax.swing.JPanel();
        nombreC = new javax.swing.JTextField();
        enviarC = new javax.swing.JButton();
        etiqNombreC = new javax.swing.JLabel();
        etiqIDAc1 = new javax.swing.JLabel();
        idArticuloBuscarC = new javax.swing.JTextField();
        lineaAc1 = new javax.swing.JSeparator();
        etiqValorC = new javax.swing.JLabel();
        etiqCantidadC = new javax.swing.JLabel();
        cantidadC = new javax.swing.JSpinner();
        valorC = new javax.swing.JTextField();
        consultaArticuloN = new javax.swing.JPanel();
        scrollConsultaN = new javax.swing.JScrollPane();
        etiqIDCN = new javax.swing.JLabel();
        etiqNombreCN = new javax.swing.JLabel();
        etiqApellidosCN = new javax.swing.JLabel();
        etiqEmailCN = new javax.swing.JLabel();
        enviarCN = new javax.swing.JButton();
        aux=0;
        list = new JList<TransferArticulo>();
        scrollConsultaN = new javax.swing.JScrollPane(list);
        

        etiqCantidadA.setText("Cantidad:");

        etiqValorA.setText("Valor:");

        enviarA.setText("Enviar");
        enviarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAActionPerformed(evt);
            }
        });

        etiqNombreA.setText("Nombre:");

        cantidadA.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        cantidadA.setEditor(new javax.swing.JSpinner.NumberEditor(cantidadA, ""));


        javax.swing.GroupLayout altaArticuloLayout = new javax.swing.GroupLayout(altaArticulo);
        altaArticulo.setLayout(altaArticuloLayout);
        altaArticuloLayout.setHorizontalGroup(
            altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaArticuloLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(cantidadA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(413, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altaArticuloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
            .addGroup(altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(altaArticuloLayout.createSequentialGroup()
                    .addGap(43, 43, 43)
                    .addGroup(altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(altaArticuloLayout.createSequentialGroup()
                            .addGroup(altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(etiqCantidadA)
                                .addComponent(etiqNombreA))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(177, 177, 177)
                            .addComponent(etiqValorA))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altaArticuloLayout.createSequentialGroup()
                            .addGap(201, 201, 201)
                            .addComponent(enviarA)
                            .addGap(188, 188, 188)))
                    .addContainerGap(61, Short.MAX_VALUE)))
        );
        altaArticuloLayout.setVerticalGroup(
            altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaArticuloLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(valorA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(cantidadA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(altaArticuloLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addGroup(altaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqNombreA)
                        .addComponent(nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqValorA))
                    .addGap(37, 37, 37)
                    .addComponent(etiqCantidadA)
                    .addGap(36, 36, 36)
                    .addComponent(enviarA)
                    .addContainerGap(171, Short.MAX_VALUE)))
        );

        panelArticulo.addTab("Alta", altaArticulo);

        nombreAc.setEditable(false);
        

        enviarAc.setText("Buscar");
        enviarAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAcActionPerformed(evt);
            }
        });

        etiqNombreAc.setText("Nombre:");

        etiqIDAc.setText("ID:");

        nuevaAc.setText("Nueva Busqueda");
        nuevaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaAcActionPerformed(evt);
            }
        });

        actualizaAc.setText("Actualizar");
        actualizaAc.setEnabled(false);
        actualizaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaAcActionPerformed(evt);
            }
        });

        lineaAc.setBackground(new java.awt.Color(0, 0, 0));

        etiqValorAc.setText("Valor:");

        etiqCantidadAc.setText("Cantidad:");

        cantidadAc.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        cantidadAc.setEditor(new javax.swing.JSpinner.NumberEditor(cantidadAc, ""));
        cantidadAc.setEnabled(false);

        valorAc.setEditable(false);
        
        javax.swing.GroupLayout actualizaArticuloLayout = new javax.swing.GroupLayout(actualizaArticulo);
        actualizaArticulo.setLayout(actualizaArticuloLayout);
        actualizaArticuloLayout.setHorizontalGroup(
            actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizaArticuloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqNombreAc)
                    .addComponent(etiqIDAc)
                    .addComponent(etiqCantidadAc))
                .addGap(18, 18, 18)
                .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreAc, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(idArticuloBuscarAc)
                    .addComponent(cantidadAc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizaArticuloLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(enviarAc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(nuevaAc))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizaArticuloLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(actualizaArticuloLayout.createSequentialGroup()
                                .addComponent(actualizaAc)
                                .addGap(34, 34, 34))
                            .addGroup(actualizaArticuloLayout.createSequentialGroup()
                                .addComponent(etiqValorAc)
                                .addGap(18, 18, 18)
                                .addComponent(valorAc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))))
                .addGap(28, 28, 28))
            .addComponent(lineaAc)
        );
        actualizaArticuloLayout.setVerticalGroup(
            actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizaArticuloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDAc)
                    .addComponent(idArticuloBuscarAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarAc)
                    .addComponent(nuevaAc))
                .addGap(30, 30, 30)
                .addComponent(lineaAc, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreAc)
                    .addComponent(etiqValorAc)
                    .addComponent(valorAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(actualizaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(actualizaAc)
                    .addComponent(etiqCantidadAc)
                    .addComponent(cantidadAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );

        panelArticulo.addTab("Actualiza", actualizaArticulo);

        nombreC.setEditable(false);
       

        enviarC.setText("Buscar");
        enviarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCActionPerformed(evt);
            }
        });

        etiqNombreC.setText("Nombre:");

        etiqIDAc1.setText("ID:");

        lineaAc1.setBackground(new java.awt.Color(0, 0, 0));

        etiqValorC.setText("Valor:");

        etiqCantidadC.setText("Cantidad:");

        cantidadC.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        cantidadC.setEditor(new javax.swing.JSpinner.NumberEditor(cantidadC, ""));
        cantidadC.setEnabled(false);

       

        javax.swing.GroupLayout consultaArticuloLayout = new javax.swing.GroupLayout(consultaArticulo);
        consultaArticulo.setLayout(consultaArticuloLayout);
        consultaArticuloLayout.setHorizontalGroup(
            consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaArticuloLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqNombreC)
                    .addComponent(etiqIDAc1)
                    .addComponent(etiqCantidadC))
                .addGap(18, 18, 18)
                .addGroup(consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombreC, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                    .addComponent(idArticuloBuscarC)
                    .addComponent(cantidadC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(consultaArticuloLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(enviarC)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaArticuloLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                        .addComponent(etiqValorC)
                        .addGap(18, 18, 18)
                        .addComponent(valorC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addGap(28, 28, 28))
            .addComponent(lineaAc1)
        );
        consultaArticuloLayout.setVerticalGroup(
            consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaArticuloLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDAc1)
                    .addComponent(idArticuloBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enviarC))
                .addGap(30, 30, 30)
                .addComponent(lineaAc1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreC)
                    .addComponent(etiqValorC)
                    .addComponent(valorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(consultaArticuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqCantidadC)
                    .addComponent(cantidadC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );

        panelArticulo.addTab("Consulta (1)", consultaArticulo);

        etiqIDCN.setText("ID");

        etiqNombreCN.setText("Nombre");

        etiqApellidosCN.setText("Cantidad");

        etiqEmailCN.setText("Valor");

        enviarCN.setText("Enviar");
        enviarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaArticuloNLayout = new javax.swing.GroupLayout(consultaArticuloN);
        consultaArticuloN.setLayout(consultaArticuloNLayout);
        consultaArticuloNLayout.setHorizontalGroup(
            consultaArticuloNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaArticuloNLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqIDCN)
                .addGap(37, 37, 37)
                .addComponent(etiqNombreCN)
                .addGap(53, 53, 53)
                .addComponent(etiqApellidosCN)
                .addGap(50, 50, 50)
                .addComponent(etiqEmailCN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(scrollConsultaN)
            .addGroup(consultaArticuloNLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(enviarCN)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        consultaArticuloNLayout.setVerticalGroup(
            consultaArticuloNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaArticuloNLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(consultaArticuloNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDCN)
                    .addComponent(etiqNombreCN)
                    .addComponent(etiqApellidosCN)
                    .addComponent(etiqEmailCN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollConsultaN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(enviarCN)
                .addContainerGap())
        );

        panelArticulo.addTab("Consulta (N)", consultaArticuloN);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArticulo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelArticulo)
        );
    }// </editor-fold>
    
    
    
    //////////////// ALTA ARTICULO ////////////////////                        

    private void enviarAActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
    	TransferArticulo articulo = new TransferArticulo(); 
    
    	if ( !nombreA.getText().equals("") 
				&& !valorA.getText().equals("")
				&& cantidadA.getValue()!=aux){
    		
    		articulo.setNombre(nombreA.getText());
    		articulo.setValor(Float.parseFloat(valorA.getText()));
    		articulo.setCantidad((int) cantidadA.getValue());

    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_ALTA_ARTICULO, articulo);
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    	
    }                                       

                                           
    ///////////// ACTUALIZAR ARTICULO /////////////

    private void enviarAcActionPerformed(java.awt.event.ActionEvent evt) {   
    	
    	idArticuloBuscarAc.setEditable(false);//Textfield
		
		String id = idArticuloBuscarAc.getText();	
		
		if ( !id.equals("") ) {
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTAR_ARTICULO_MODIFICAR, Integer.valueOf(id));
		}
		else
		{
			JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
		}
    }                                        
    
    private void nuevaAcActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	idArticulo = null;
    	
    	idArticuloBuscarAc.setText("");
    	idArticuloBuscarAc.setEditable(true);
		
    	nombreAc.setText("");
		nombreAc.setEditable(false);
		valorAc.setText("");
		valorAc.setEditable(false);
		cantidadAc.setValue(0);
		cantidadAc.setEnabled(true);
		
    }
    
    private void actualizaAcActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	idArticuloBuscarAc.setEditable(false);
		
		TransferArticulo articulo = new TransferArticulo();
		
		if ( idArticulo != null 
				&& !nombreAc.getText().equals("") 
				&& !valorAc.getText().equals("")
				&& cantidadAc.getValue()!=aux) {
			
    		articulo.setID(idArticulo);
			articulo.setNombre(nombreAc.getText());
    		articulo.setValor(Float.parseFloat(valorAc.getText()));
    		articulo.setCantidad((int) cantidadAc.getValue());

			
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_MODIFICAR_ARTICULO, articulo);
			
		}
		else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    }                                        

  
    /////////// CONSULTAR ARTICULO /////////////
    private void enviarCActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	String id= idArticuloBuscarC.getText();
    	
    	if ( !id.equals("") ) {

			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_ARTICULO, Integer.valueOf(id));
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    }                                       

   

    private void enviarCNActionPerformed(java.awt.event.ActionEvent evt){
		
		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_TODOS_ARTICULOS, null);
    }
    
    ///////////////////////// Actualizar ///////////////////////
    
    public void actualizarVentanaAlta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_ALTA_ARTICULO == idEvento ) {
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {

		    		nombreA.setText(""); 
					valorA.setText(""); 
					cantidadA.setValue(0);
					
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Articulo creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al crear el socio", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.ERROR_EVENTO_ALTA_ARTICULO == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		
		
	}

    public void actualizarVentanaConsulta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_CONSULTA_ARTICULO == idEvento ) {
		
			if ( datos instanceof TransferArticulo) {
				
				TransferArticulo articulo = (TransferArticulo) datos;
				
				if ( articulo != null ) {
					
					nombreC.setText(articulo.getNombre());
					valorC.setText(articulo.getValor().toString());
					cantidadC.setValue(articulo.getCantidad());
				}		
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar el articulo", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		else if ( IDEventos.ERROR_EVENTO_CONSULTA_ARTICULO == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
	}
    
    public void actualizarVentanaActualiza(IDEventos idEvento, Object datos){
	    
    	if ( IDEventos.EVENTO_MODIFICAR_ARTICULO == idEvento ) {
			
			if ( datos instanceof Boolean ) {
				
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
					
					nombreAc.setText("");
					nombreAc.setEditable(false);
					valorAc.setText("");
					valorAc.setEditable(false);
					cantidadAc.setValue(0);
					cantidadAc.setEnabled(true);
					
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame, "Articulo modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame, "El articulo no se ha modificado", "Error", JOptionPane.ERROR_MESSAGE);
				}
				idArticulo = null;
			}
		}
		else if ( IDEventos.EVENTO_CONSULTAR_ARTICULO_MODIFICAR == idEvento ) {
			
			if ( datos instanceof TransferArticulo) {
				
				TransferArticulo articulo = (TransferArticulo) datos;
					
				idArticulo = articulo.getID();
				nombreAc.setText(articulo.getNombre());
				nombreAc.setEditable(true);
				valorAc.setText(articulo.getValor().toString());
				valorAc.setEditable(true);
				cantidadAc.setValue(articulo.getCantidad());
				cantidadAc.setEnabled(true);
				actualizaAc.setEnabled(true);
			}
		}
		else if ( IDEventos.ERROR_EVENTO_MODIFICAR_ARTICULO == idEvento || IDEventos.ERROR_EVENTO_CONSULTAR_ARTICULO_MODIFICAR == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
    }
    
    public void actualizarVentanaConsultaN(IDEventos idEvento, Object datos) {

    	if ( IDEventos.EVENTO_CONSULTA_TODOS_ARTICULOS == idEvento ) {
    		
    		if ( datos instanceof ArrayList) {

    			@SuppressWarnings("unchecked")
    			ArrayList<TransferArticulo> listaArticulos = (ArrayList<TransferArticulo>) datos;

    			TransferArticulo[] articulos = new TransferArticulo[listaArticulos.size()];
    			listaArticulos.toArray(articulos);
    			
    			list.setListData(articulos);

    		}
    		else {
    			JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar todos los articulos", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    	else if ( IDEventos.ERROR_EVENTO_CONSULTA_TODOS_ARTICULOS== idEvento ) {

    		if ( datos instanceof ExcepcionSQL ) {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		else {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }
    
    
    
  

    // Variables declaration - do not modify                     
    private javax.swing.JButton actualizaAc;
    private javax.swing.JPanel actualizaArticulo;
    private javax.swing.JPanel altaArticulo;
    private javax.swing.JSpinner cantidadA;
    private javax.swing.JSpinner cantidadAc;
    private javax.swing.JSpinner cantidadC;
    private javax.swing.JPanel consultaArticulo;
    private javax.swing.JPanel consultaArticuloN;
    private javax.swing.JButton enviarA;
    private javax.swing.JButton enviarAc;
    private javax.swing.JButton enviarC;
    private javax.swing.JButton enviarCN;
    private javax.swing.JLabel etiqApellidosCN;
    private javax.swing.JLabel etiqCantidadA;
    private javax.swing.JLabel etiqCantidadAc;
    private javax.swing.JLabel etiqCantidadC;
    private javax.swing.JLabel etiqEmailCN;
    private javax.swing.JLabel etiqIDAc;
    private javax.swing.JLabel etiqIDAc1;
    private javax.swing.JLabel etiqIDCN;
    private javax.swing.JLabel etiqNombreA;
    private javax.swing.JLabel etiqNombreAc;
    private javax.swing.JLabel etiqNombreC;
    private javax.swing.JLabel etiqNombreCN;
    private javax.swing.JLabel etiqValorA;
    private javax.swing.JLabel etiqValorAc;
    private javax.swing.JLabel etiqValorC;
    private javax.swing.JTextField idArticuloBuscarAc;
    private javax.swing.JTextField idArticuloBuscarC;
    private javax.swing.JSeparator lineaAc;
    private javax.swing.JSeparator lineaAc1;
    private javax.swing.JTextField nombreA;
    private javax.swing.JTextField nombreAc;
    private javax.swing.JTextField nombreC;
    private javax.swing.JButton nuevaAc;
    private javax.swing.JTabbedPane panelArticulo;
    private javax.swing.JScrollPane scrollConsultaN;
    private javax.swing.JTextField valorA;
    private javax.swing.JTextField valorAc;
    private javax.swing.JTextField valorC;
    private JList<TransferArticulo> list;
    private Integer idArticulo;
    private Integer aux;
}
