/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.trabajador.paneles;

import java.util.List;

import integracion.transacciones.conexion.ExcepcionSQL;

import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

import negocio.articulo.TransferArticulo;
import negocio.cliente.TransferCliente;
import negocio.trabajador.TransferTrabajador;
import presentacion.cliente.paneles.*;
import presentacion.comando.IDEventos;
import presentacion.controlador.Controlador;
import sun.util.calendar.BaseCalendar.Date;

/**
 *
 * @author ReplacedKevin
 */
public class PanelTrabajador extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form prueba
     */
    public PanelTrabajador() {
        initComponents();
        botones();
        valor="Empleado";
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    
    private void initComponents() {

        panelTrabajador = new javax.swing.JTabbedPane();
        altaTrabajador = new javax.swing.JPanel();
        tipoA = new javax.swing.JComboBox();
        etiqNombreA = new javax.swing.JLabel();
        nombreA = new javax.swing.JTextField();
        etiqDNIA = new javax.swing.JLabel();
        dniA = new javax.swing.JTextField();
        etiqApellidosA = new javax.swing.JLabel();
        apellidosA = new javax.swing.JTextField();
        etiqFec_inicioA = new javax.swing.JLabel();
        etiqFec_finalA = new javax.swing.JLabel();
        etiqHorasA = new javax.swing.JLabel();
        horasA = new javax.swing.JTextField();
        etiqSueldo_horasA = new javax.swing.JLabel();
        sueldo_horasA = new javax.swing.JTextField();
        etiqFactor_productividadA = new javax.swing.JLabel();
        factor_productividadA = new javax.swing.JTextField();
        enviarA = new javax.swing.JButton();
        etiqSueldo_baseA = new javax.swing.JLabel();
        sueldo_baseA = new javax.swing.JTextField();
        fec_inicioA = new javax.swing.JFormattedTextField();
        fec_finalA = new javax.swing.JFormattedTextField();
        bajaTrabajador = new javax.swing.JPanel();
        nombreB = new javax.swing.JTextField();
        dniB = new javax.swing.JTextField();
        etiqDNIB = new javax.swing.JLabel();
        enviarB = new javax.swing.JButton();
        etiqApellidosC = new javax.swing.JLabel();
        apellidosB = new javax.swing.JTextField();
        etiqNombreB = new javax.swing.JLabel();
        etiqIDB = new javax.swing.JLabel();
        idBuscarTrabajadorB = new javax.swing.JTextField();
        lineaB1 = new javax.swing.JSeparator();
        tipoTrabajadorB = new javax.swing.JCheckBox();
        sueldo_horasB = new javax.swing.JTextField();
        fec_finalB = new javax.swing.JFormattedTextField();
        horasB = new javax.swing.JTextField();
        sueldo_baseB = new javax.swing.JTextField();
        fec_inicioB = new javax.swing.JFormattedTextField();
        etiqSueldo_baseA1 = new javax.swing.JLabel();
        etiqSueldo_horasA1 = new javax.swing.JLabel();
        factor_productividadB = new javax.swing.JTextField();
        etiqFactor_productividadA1 = new javax.swing.JLabel();
        etiqHorasB = new javax.swing.JLabel();
        etiqFec_finalB = new javax.swing.JLabel();
        etiqFec_inicioA1 = new javax.swing.JLabel();
        borraB = new javax.swing.JButton();
        actualizarTrabajador = new javax.swing.JPanel();
        nombreAc = new javax.swing.JTextField();
        dniAc = new javax.swing.JTextField();
        etiqdniC1 = new javax.swing.JLabel();
        enviarAc = new javax.swing.JButton();
        etiqApellidosAc = new javax.swing.JLabel();
        apellidosAc = new javax.swing.JTextField();
        etiqNombreAc = new javax.swing.JLabel();
        etiqIDAc = new javax.swing.JLabel();
        idBuscarTrabajadorAc = new javax.swing.JTextField();
        lineaB2 = new javax.swing.JSeparator();
        tipoTrabajadorAc = new javax.swing.JCheckBox();
        sueldo_horasAc = new javax.swing.JTextField();
        fec_finalAc = new javax.swing.JFormattedTextField();
        horasAc = new javax.swing.JTextField();
        sueldo_baseAc = new javax.swing.JTextField();
        fec_inicioAc = new javax.swing.JFormattedTextField();
        etiqSueldo_baseAc = new javax.swing.JLabel();
        etiqSueldo_horasAc = new javax.swing.JLabel();
        factor_productividadAc = new javax.swing.JTextField();
        etiqFactor_productividadA2 = new javax.swing.JLabel();
        etiqHorasAc = new javax.swing.JLabel();
        etiqFec_finalAc = new javax.swing.JLabel();
        etiqFec_inicioA2 = new javax.swing.JLabel();
        actualizaAc = new javax.swing.JButton();
        nuevaAc = new javax.swing.JButton();
        consultaTrabajador = new javax.swing.JPanel();
        nombreC1 = new javax.swing.JTextField();
        dniC1 = new javax.swing.JTextField();
        etiqDNIB2 = new javax.swing.JLabel();
        enviarC1 = new javax.swing.JButton();
        etiqApellidosC1 = new javax.swing.JLabel();
        apellidosC1 = new javax.swing.JTextField();
        etiqNombreC1 = new javax.swing.JLabel();
        etiqIDC = new javax.swing.JLabel();
        idBuscarTrabajadorC = new javax.swing.JTextField();
        lineaB3 = new javax.swing.JSeparator();
        tipoTrabajadorC1 = new javax.swing.JCheckBox();
        sueldo_horasC1 = new javax.swing.JTextField();
        fec_finalC1 = new javax.swing.JFormattedTextField();
        horasC1 = new javax.swing.JTextField();
        sueldo_baseC1 = new javax.swing.JTextField();
        fec_inicioC1 = new javax.swing.JFormattedTextField();
        etiqSueldo_baseC1 = new javax.swing.JLabel();
        etiqSueldo_horasC1 = new javax.swing.JLabel();
        factor_productividadC1 = new javax.swing.JTextField();
        etiqFactor_productividadC1 = new javax.swing.JLabel();
        etiqHorasC1 = new javax.swing.JLabel();
        etiqFec_finalC1 = new javax.swing.JLabel();
        etiqFec_inicioC1 = new javax.swing.JLabel();
        consultaNTrabajador = new javax.swing.JPanel();
        scrollConsultaN = new javax.swing.JScrollPane();
        etiqIDCN = new javax.swing.JLabel();
        etiqNombreCN = new javax.swing.JLabel();
        etiqApellidosCN = new javax.swing.JLabel();
        etiqEmailCN = new javax.swing.JLabel();
        etiqTelefonoCN = new javax.swing.JLabel();
        enviarCN = new javax.swing.JButton();
        list = new JList<TransferTrabajador>();
        scrollConsultaN = new javax.swing.JScrollPane(list);
        
        

        tipoA.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Empleado", "Encargado" }));
        tipoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoAActionPerformed(evt);
            }
        });

        etiqNombreA.setText("Nombre:");

       
        etiqDNIA.setText("DNI:");

        etiqApellidosA.setText("Apellidos:");

        etiqFec_inicioA.setText("Fecha Inicio:");

        etiqFec_finalA.setText("Fecha Fin:");

        etiqHorasA.setText("Horas:");

        etiqSueldo_horasA.setText("Sueldo x horas:");

        etiqFactor_productividadA.setText("Fractor Prod:");

        enviarA.setText("Enviar");
        enviarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAActionPerformed(evt);
            }
        });

        etiqSueldo_baseA.setText("Sueldo Base:");

        fec_inicioA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_inicioA.setToolTipText("");

        fec_finalA.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_finalA.setToolTipText("");

        javax.swing.GroupLayout altaTrabajadorLayout = new javax.swing.GroupLayout(altaTrabajador);
        altaTrabajador.setLayout(altaTrabajadorLayout);
        altaTrabajadorLayout.setHorizontalGroup(
            altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaTrabajadorLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqFec_finalA)
                    .addComponent(etiqApellidosA)
                    .addComponent(etiqNombreA)
                    .addComponent(etiqFactor_productividadA)
                    .addComponent(etiqHorasA))
                .addGap(18, 18, 18)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, altaTrabajadorLayout.createSequentialGroup()
                        .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(altaTrabajadorLayout.createSequentialGroup()
                                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nombreA, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(apellidosA)
                                        .addComponent(fec_finalA))
                                    .addComponent(horasA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etiqDNIA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiqFec_inicioA, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etiqSueldo_horasA, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(altaTrabajadorLayout.createSequentialGroup()
                                .addComponent(factor_productividadA, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(etiqSueldo_baseA)))
                        .addGap(18, 18, 18)
                        .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dniA, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(sueldo_horasA)
                            .addComponent(sueldo_baseA)
                            .addComponent(fec_inicioA))
                        .addGap(60, 60, 60))
                    .addGroup(altaTrabajadorLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(tipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(altaTrabajadorLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(enviarA)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        altaTrabajadorLayout.setVerticalGroup(
            altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(altaTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqNombreA)
                    .addComponent(nombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDNIA)
                    .addComponent(dniA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqApellidosA)
                    .addComponent(apellidosA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqFec_inicioA)
                    .addComponent(fec_inicioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqFec_finalA)
                    .addComponent(fec_finalA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqSueldo_horasA)
                    .addComponent(sueldo_horasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqHorasA)
                    .addComponent(horasA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(altaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqFactor_productividadA)
                    .addComponent(factor_productividadA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqSueldo_baseA)
                    .addComponent(sueldo_baseA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(enviarA)
                .addGap(65, 65, 65))
        );

        panelTrabajador.addTab("Alta", altaTrabajador);

        nombreB.setEditable(false);
        

        dniB.setEditable(false);

        etiqDNIB.setText("DNI:");

        enviarB.setText("Buscar");
        enviarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarBActionPerformed(evt);
            }
        });

        etiqApellidosC.setText("Apellidos:");

        apellidosB.setEditable(false);

        etiqNombreB.setText("Nombre:");

        etiqIDB.setText("ID:");

        lineaB1.setBackground(new java.awt.Color(0, 0, 0));

        tipoTrabajadorB.setText("Encargado");
        tipoTrabajadorB.setEnabled(false);
        

        sueldo_horasB.setEditable(false);
        

        fec_finalB.setEditable(false);
        fec_finalB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_finalB.setToolTipText("");

        horasB.setEditable(false);

        sueldo_baseB.setEditable(false);

        fec_inicioB.setEditable(false);
        fec_inicioB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_inicioB.setToolTipText("");

        etiqSueldo_baseA1.setText("Sueldo Base:");

        etiqSueldo_horasA1.setText("Sueldo x horas:");

        factor_productividadB.setEditable(false);

        etiqFactor_productividadA1.setText("Fractor Prod:");

        etiqHorasB.setText("Horas:");

        etiqFec_finalB.setText("Fecha Fin:");

        etiqFec_inicioA1.setText("Fecha Inicio:");

        borraB.setText("Borrar");
        borraB.setEnabled(false);
        borraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borraBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bajaTrabajadorLayout = new javax.swing.GroupLayout(bajaTrabajador);
        bajaTrabajador.setLayout(bajaTrabajadorLayout);
        bajaTrabajadorLayout.setHorizontalGroup(
            bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                .addComponent(lineaB1)
                .addContainerGap())
            .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqHorasB)
                    .addComponent(etiqFec_finalB)
                    .addComponent(etiqIDB)
                    .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                        .addComponent(etiqDNIB)
                        .addGap(26, 26, 26))
                    .addComponent(etiqNombreB))
                .addGap(18, 18, 18)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                        .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dniB)
                            .addComponent(idBuscarTrabajadorB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fec_finalB)
                            .addComponent(nombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(enviarB)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                        .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                                        .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(etiqFec_inicioA1)
                                            .addComponent(etiqApellidosC)
                                            .addComponent(etiqSueldo_baseA1)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bajaTrabajadorLayout.createSequentialGroup()
                                        .addComponent(horasB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(etiqSueldo_horasA1)))
                                .addGap(18, 18, 18)
                                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sueldo_baseB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(sueldo_horasB, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fec_inicioB, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(borraB)
                                .addGap(61, 61, 61)))
                        .addGap(47, 47, 47))))
            .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoTrabajadorB)
                    .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                        .addComponent(etiqFactor_productividadA1)
                        .addGap(18, 18, 18)
                        .addComponent(factor_productividadB, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        bajaTrabajadorLayout.setVerticalGroup(
            bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bajaTrabajadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idBuscarTrabajadorB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqIDB)
                    .addComponent(enviarB))
                .addGap(18, 18, 18)
                .addComponent(lineaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreB)
                    .addComponent(etiqApellidosC)
                    .addComponent(apellidosB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqDNIB)
                    .addComponent(etiqFec_inicioA1)
                    .addComponent(fec_inicioB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqFec_finalB)
                    .addComponent(fec_finalB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqHorasB)
                    .addComponent(etiqSueldo_horasA1)
                    .addComponent(sueldo_horasB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqFactor_productividadA1)
                    .addComponent(factor_productividadB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqSueldo_baseA1)
                    .addComponent(sueldo_baseB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(bajaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoTrabajadorB)
                    .addComponent(borraB))
                .addGap(50, 50, 50))
        );

        panelTrabajador.addTab("Baja", bajaTrabajador);

        nombreAc.setEditable(false);
        

        dniAc.setEditable(false);

        etiqdniC1.setText("DNI:");

        enviarAc.setText("Buscar");
        enviarAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarAcActionPerformed(evt);
            }
        });

        etiqApellidosAc.setText("Apellidos:");

        apellidosAc.setEditable(false);

        etiqNombreAc.setText("Nombre:");

        etiqIDAc.setText("ID:");

        lineaB2.setBackground(new java.awt.Color(0, 0, 0));

        tipoTrabajadorAc.setText("Encargado");
        tipoTrabajadorAc.setEnabled(false);
        

        sueldo_horasAc.setEditable(false);
        

        fec_finalAc.setEditable(false);
        fec_finalAc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_finalAc.setToolTipText("");

        horasAc.setEditable(false);

        sueldo_baseAc.setEditable(false);

        fec_inicioAc.setEditable(false);
        fec_inicioAc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_inicioAc.setToolTipText("");

        etiqSueldo_baseAc.setText("Sueldo Base:");

        etiqSueldo_horasAc.setText("Sueldo x horas:");

        factor_productividadAc.setEditable(false);

        etiqFactor_productividadA2.setText("Fractor Prod:");

        etiqHorasAc.setText("Horas:");

        etiqFec_finalAc.setText("Fecha Fin:");

        etiqFec_inicioA2.setText("Fecha Inicio:");

        actualizaAc.setText("Actualizar");
        actualizaAc.setEnabled(false);
        actualizaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaAcActionPerformed(evt);
            }
        });

        nuevaAc.setText("Nueva Busqueda");
        nuevaAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaAcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actualizarTrabajadorLayout = new javax.swing.GroupLayout(actualizarTrabajador);
        actualizarTrabajador.setLayout(actualizarTrabajadorLayout);
        actualizarTrabajadorLayout.setHorizontalGroup(
            actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                .addComponent(lineaB2)
                .addContainerGap())
            .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqHorasAc)
                    .addComponent(etiqFec_finalAc)
                    .addComponent(etiqIDAc)
                    .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                        .addComponent(etiqdniC1)
                        .addGap(26, 26, 26))
                    .addComponent(etiqNombreAc))
                .addGap(18, 18, 18)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                        .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(etiqFec_inicioA2)
                                            .addComponent(etiqApellidosAc)
                                            .addComponent(etiqSueldo_baseAc)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actualizarTrabajadorLayout.createSequentialGroup()
                                        .addComponent(horasAc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(etiqSueldo_horasAc)))
                                .addGap(18, 18, 18)
                                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(apellidosAc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sueldo_baseAc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                        .addComponent(sueldo_horasAc, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fec_inicioAc, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(actualizaAc)
                                .addGap(61, 61, 61)))
                        .addGap(47, 47, 47))
                    .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                        .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dniAc)
                            .addComponent(idBuscarTrabajadorAc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fec_finalAc)
                            .addComponent(nombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addComponent(enviarAc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(nuevaAc)
                        .addGap(45, 45, 45))))
            .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoTrabajadorAc)
                    .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                        .addComponent(etiqFactor_productividadA2)
                        .addGap(18, 18, 18)
                        .addComponent(factor_productividadAc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        actualizarTrabajadorLayout.setVerticalGroup(
            actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actualizarTrabajadorLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idBuscarTrabajadorAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqIDAc)
                    .addComponent(enviarAc)
                    .addComponent(nuevaAc))
                .addGap(18, 18, 18)
                .addComponent(lineaB2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqNombreAc)
                    .addComponent(etiqApellidosAc)
                    .addComponent(apellidosAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dniAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqdniC1)
                    .addComponent(etiqFec_inicioA2)
                    .addComponent(fec_inicioAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqFec_finalAc)
                    .addComponent(fec_finalAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horasAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqHorasAc)
                    .addComponent(etiqSueldo_horasAc)
                    .addComponent(sueldo_horasAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqFactor_productividadA2)
                    .addComponent(factor_productividadAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiqSueldo_baseAc)
                    .addComponent(sueldo_baseAc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(actualizarTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoTrabajadorAc)
                    .addComponent(actualizaAc))
                .addGap(50, 50, 50))
        );

        panelTrabajador.addTab("Actualizar", actualizarTrabajador);

        nombreC1.setEditable(false);
        

        dniC1.setEditable(false);

        etiqDNIB2.setText("DNI:");

        enviarC1.setText("Buscar");
        enviarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarC1ActionPerformed(evt);
            }
        });

        etiqApellidosC1.setText("Apellidos:");

        apellidosC1.setEditable(false);

        etiqNombreC1.setText("Nombre:");

        etiqIDC.setText("ID:");

        lineaB3.setBackground(new java.awt.Color(0, 0, 0));

        tipoTrabajadorC1.setText("Encargado");
        tipoTrabajadorC1.setEnabled(false);
        

        sueldo_horasC1.setEditable(false);
        

        fec_finalC1.setEditable(false);
        fec_finalC1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_finalC1.setToolTipText("");

        horasC1.setEditable(false);

        sueldo_baseC1.setEditable(false);

        fec_inicioC1.setEditable(false);
        fec_inicioC1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MM/yyyy"))));
        fec_inicioC1.setToolTipText("");

        etiqSueldo_baseC1.setText("Sueldo Base:");

        etiqSueldo_horasC1.setText("Sueldo x horas:");

        factor_productividadC1.setEditable(false);

        etiqFactor_productividadC1.setText("Fractor Prod:");

        etiqHorasC1.setText("Horas:");

        etiqFec_finalC1.setText("Fecha Fin:");

        etiqFec_inicioC1.setText("Fecha Inicio:");

        javax.swing.GroupLayout consultaTrabajadorLayout = new javax.swing.GroupLayout(consultaTrabajador);
        consultaTrabajador.setLayout(consultaTrabajadorLayout);
        consultaTrabajadorLayout.setHorizontalGroup(
            consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 633, Short.MAX_VALUE)
            .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lineaB3)
                        .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(etiqHorasC1)
                                .addComponent(etiqFec_finalC1)
                                .addComponent(etiqIDC)
                                .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                                    .addComponent(etiqDNIB2)
                                    .addGap(26, 26, 26))
                                .addComponent(etiqNombreC1))
                            .addGap(18, 18, 18)
                            .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dniC1)
                                        .addComponent(idBuscarTrabajadorC, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fec_finalC1)
                                        .addComponent(nombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(65, 65, 65)
                                    .addComponent(enviarC1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(etiqFec_inicioC1)
                                                .addComponent(etiqApellidosC1)
                                                .addComponent(etiqSueldo_baseC1)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaTrabajadorLayout.createSequentialGroup()
                                            .addComponent(horasC1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(etiqSueldo_horasC1)))
                                    .addGap(18, 18, 18)
                                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(apellidosC1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(sueldo_baseC1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                            .addComponent(sueldo_horasC1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fec_inicioC1, javax.swing.GroupLayout.Alignment.LEADING)))
                                    .addGap(41, 41, 41))))
                        .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                            .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tipoTrabajadorC1)
                                .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                                    .addComponent(etiqFactor_productividadC1)
                                    .addGap(18, 18, 18)
                                    .addComponent(factor_productividadC1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(412, 412, 412)))
                    .addGap(3, 3, 3)))
        );
        consultaTrabajadorLayout.setVerticalGroup(
            consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 452, Short.MAX_VALUE)
            .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(consultaTrabajadorLayout.createSequentialGroup()
                    .addGap(36, 36, 36)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idBuscarTrabajadorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqIDC)
                        .addComponent(enviarC1))
                    .addGap(18, 18, 18)
                    .addComponent(lineaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqNombreC1)
                        .addComponent(etiqApellidosC1)
                        .addComponent(apellidosC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(36, 36, 36)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dniC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqDNIB2)
                        .addComponent(etiqFec_inicioC1)
                        .addComponent(fec_inicioC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqFec_finalC1)
                        .addComponent(fec_finalC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(32, 32, 32)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(horasC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqHorasC1)
                        .addComponent(etiqSueldo_horasC1)
                        .addComponent(sueldo_horasC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(consultaTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(etiqFactor_productividadC1)
                        .addComponent(factor_productividadC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(etiqSueldo_baseC1)
                        .addComponent(sueldo_baseC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addComponent(tipoTrabajadorC1)
                    .addGap(37, 37, 37)))
        );

        panelTrabajador.addTab("Consulta (1)", consultaTrabajador);

        etiqIDCN.setText("ID_Trabajador");

        etiqNombreCN.setText("ID_Departamento");

        etiqApellidosCN.setText("Apellidos");

        etiqEmailCN.setText("Email");

        etiqTelefonoCN.setText("Telefono");

        enviarCN.setText("Enviar");
        enviarCN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarCNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaNTrabajadorLayout = new javax.swing.GroupLayout(consultaNTrabajador);
        consultaNTrabajador.setLayout(consultaNTrabajadorLayout);
        consultaNTrabajadorLayout.setHorizontalGroup(
            consultaNTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollConsultaN)
            .addGroup(consultaNTrabajadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqIDCN)
                .addGap(34, 34, 34)
                .addComponent(etiqNombreCN)
                .addGap(52, 52, 52)
                .addComponent(etiqApellidosCN)
                .addGap(47, 47, 47)
                .addComponent(etiqEmailCN)
                .addGap(58, 58, 58)
                .addComponent(etiqTelefonoCN)
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(consultaNTrabajadorLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(enviarCN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        consultaNTrabajadorLayout.setVerticalGroup(
            consultaNTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, consultaNTrabajadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(consultaNTrabajadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqIDCN)
                    .addComponent(etiqNombreCN)
                    .addComponent(etiqApellidosCN)
                    .addComponent(etiqEmailCN)
                    .addComponent(etiqTelefonoCN))
                .addGap(18, 18, 18)
                .addComponent(scrollConsultaN, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(enviarCN)
                .addGap(22, 22, 22))
        );

        panelTrabajador.addTab("Consulta (N)", consultaNTrabajador);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajador, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTrabajador)
        );
    }// </editor-fold>

    //////////////////ALTA TRABAJADOR ///////////////////
    private void tipoAActionPerformed(java.awt.event.ActionEvent evt) {                                      

        valor = (String) tipoA.getSelectedItem();

        if(valor.equalsIgnoreCase("Empleado"))
        {
            fec_finalA.setVisible(true);
            etiqFec_finalA.setVisible(true);
            fec_inicioA.setVisible(true);
            etiqFec_inicioA.setVisible(true);
            dniA.setVisible(true);
            etiqDNIA.setVisible(true);
            etiqApellidosA.setVisible(true);
            apellidosA.setVisible(true);
            nombreA.setVisible(true);
            etiqNombreA.setVisible(true);
            etiqSueldo_horasA.setVisible(true);
            sueldo_horasA.setVisible(true);
            horasA.setVisible(true);
            etiqHorasA.setVisible(true);
            sueldo_baseA.setVisible(false);
            etiqSueldo_baseA.setVisible(false);
            factor_productividadA.setVisible(false);
            etiqFactor_productividadA.setVisible(false);
        }
        else
        {
            fec_finalA.setVisible(true);
            etiqFec_finalA.setVisible(true);
            fec_inicioA.setVisible(true);
            etiqFec_inicioA.setVisible(true);
            dniA.setVisible(true);
            etiqDNIA.setVisible(true);
            etiqApellidosA.setVisible(true);
            apellidosA.setVisible(true);
            nombreA.setVisible(true);
            etiqNombreA.setVisible(true);
            etiqSueldo_horasA.setVisible(false);
            sueldo_horasA.setVisible(false);
            horasA.setVisible(false);
            etiqHorasA.setVisible(false);
            sueldo_baseA.setVisible(true);
            etiqSueldo_baseA.setVisible(true);
            factor_productividadA.setVisible(true);
            etiqFactor_productividadA.setVisible(true);
        }

    }                                     
                                     
    private void enviarAActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
    	TransferTrabajador trabajador = new TransferTrabajador(); 
    	
    	if(valor.equalsIgnoreCase("Empleado"))
    	{
	    	if ( !nombreA.getText().equals("") 
					&& !apellidosA.getText().equals("")
					&& !dniA.getText().equals("") 
					&& !fec_finalA.getText().equals("")
					&& !fec_inicioA.getText().equals("")
					&& !horasA.getText().equals("")
					&& !sueldo_horasA.getText().equals("")){
	    		
	    		
	    		String fecha[] = fec_inicioA.getText().split("/");
	    		String fecha2[] = fec_finalA.getText().split("/");
	    		java.sql.Date fechainicio= new java.sql.Date(0);
	    		fechainicio.setDate(Integer.valueOf(fecha[0]));
	    		fechainicio.setMonth(Integer.valueOf(fecha[1]));
	    		fechainicio.setYear(Integer.valueOf(fecha[2]));
	    		
	    		java.sql.Date fechafin = new java.sql.Date(0);
	    		fechafin.setDate(Integer.valueOf(fecha2[0]));
	    		fechafin.setMonth(Integer.valueOf(fecha2[1]));
	    		fechafin.setYear(Integer.valueOf(fecha2[2]));
	    		
	    		
	    		trabajador.setNombre(nombreA.getText());
	    		trabajador.setApellidos(apellidosA.getText());
	    		trabajador.setDNI(dniA.getText());
	    		trabajador.setFecIni(fechainicio);
	    		trabajador.setFecFin(fechafin); 		
	    		trabajador.setTipo(false);
	    		trabajador.setHoras(Integer.parseInt(horasA.getText())); //Horas es un textfield modificado para que acepte int
	    		trabajador.setSueldoHoras(Float.parseFloat(sueldo_horasA.getText()));
	    		
	    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_ALTA_EMPLEADO, trabajador);
	    	}
	    	else
	    	{
	    		JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
	    	}
	    }
    	else
    	{

	    	if (!nombreA.getText().equals("") 
	    			&& !apellidosA.getText().equals("")
					&& !dniA.getText().equals("") 
					&& !fec_finalA.getText().equals("")
					&& !fec_inicioA.getText().equals("")
					&& !factor_productividadA.getText().equals("")
					&& !sueldo_baseA.getText().equals("")){
	    		
	    		

	    		String fecha[] = fec_inicioA.getText().split("/");
	    		String fecha2[] = fec_finalA.getText().split("/");
	    		java.sql.Date fechainicio = new java.sql.Date(0);
	    		fechainicio.setDate(Integer.valueOf(fecha[0]));
	    		fechainicio.setMonth(Integer.valueOf(fecha[1]));
	    		fechainicio.setYear(Integer.valueOf(fecha[2]));
	    		
	    		java.sql.Date fechafin =new java.sql.Date(0);;
	    		fechafin.setDate(Integer.valueOf(fecha2[0]));
	    		fechafin.setMonth(Integer.valueOf(fecha2[1]));
	    		fechafin.setYear(Integer.valueOf(fecha2[2]));
	    		
	    		
	    		trabajador.setNombre(nombreA.getText());
	    		trabajador.setApellidos(apellidosA.getText());
	    		trabajador.setDNI(dniA.getText());
	    		trabajador.setFecIni(fechainicio);
	    		trabajador.setFecFin(fechafin); 		
	    		trabajador.setTipo(true);
	    		trabajador.setFactProd(Float.parseFloat(factor_productividadA.getText())); //Horas es un textfield modificado para que acepte int
	    		trabajador.setSueldoBase(Float.parseFloat(sueldo_baseA.getText()));
	    		
	    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_ALTA_ENCARGADO, trabajador);
	    	}
	    	else
	    	{
	    		JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
	    	}
    	}
    	
        
    }                                       
                                
    ////////////////// BAJA TRABAJADOR ///////////////////
    private void enviarBActionPerformed(java.awt.event.ActionEvent evt) {                                        
    	
    	String id = idBuscarTrabajadorB.getText();

    	if ( !id.equals("") ) {
    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTAR_TRABAJADOR_BORRAR, Integer.valueOf(id));
    	}
    	else {
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    }                                       
    
    private void borraBActionPerformed(java.awt.event.ActionEvent evt){
    	
    	if ( idTrabajador != null )
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_BAJA_TRABAJADOR, idTrabajador);
		else
		{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Error al cargar el trabajador", "Error", JOptionPane.ERROR_MESSAGE);
		}
    }
                     
    ////////////////// ACTUALIZAR TRABAJADOR /////////////////
    private void enviarAcActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	
    	idBuscarTrabajadorAc.setEditable(false);//TextField
		
		String id = idBuscarTrabajadorAc.getText();	
		if ( !id.equals("") ) {
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTAR_TRABAJADOR_MODIFICAR, Integer.valueOf(id));
		}
		else
		{
			JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
		}
    	
    }                                        

    private void nuevaAcActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	idTrabajador = null;
    	idBuscarTrabajadorAc.setText("");
    	idBuscarTrabajadorAc.setEditable(false);
		
    	nombreAc.setText("");
		nombreAc.setEditable(false);
		apellidosAc.setText("");
		apellidosAc.setEditable(false);
		dniAc.setText("");
		dniAc.setEditable(false);
		fec_finalAc.setText("");
		fec_finalAc.setEditable(false);
		fec_inicioAc.setText("");
		fec_inicioAc.setEditable(false);
		sueldo_baseAc.setText("");
		sueldo_baseAc.setEditable(false);
		sueldo_horasAc.setText("");
		sueldo_horasAc.setEditable(false);
		factor_productividadAc.setText("");
		factor_productividadAc.setEditable(false);
		horasAc.setText("");
		horasAc.setEditable(false);
		tipoTrabajadorAc.setSelected(false);
		
    }
    
    private void actualizaAcActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	idBuscarTrabajadorAc.setEditable(false);
		
		TransferTrabajador trabajador = new TransferTrabajador();
		
		if(!tipoTrabajadorAc.isSelected()){
			if ( !nombreAc.getText().equals("") 
					&& !apellidosAc.getText().equals("")
					&& !dniAc.getText().equals("") 
					&& !fec_finalAc.getText().equals("")
					&& !fec_inicioAc.getText().equals("")
					&& !horasAc.getText().equals("")
					&& !sueldo_horasAc.getText().equals("")) {
				
				String fecha[] = fec_inicioAc.getText().split("/");
	    		String fecha2[] = fec_finalAc.getText().split("/");
	    		java.sql.Date fechainicio = new java.sql.Date(0);
	    		fechainicio.setDate(Integer.valueOf(fecha[0]));
	    		fechainicio.setMonth(Integer.valueOf(fecha[1]));
	    		fechainicio.setYear(Integer.valueOf(fecha[2]));
	    		
	    		java.sql.Date fechafin= new java.sql.Date(0);
	    		fechafin.setDate(Integer.valueOf(fecha2[0]));
	    		fechafin.setMonth(Integer.valueOf(fecha2[1]));
	    		fechafin.setYear(Integer.valueOf(fecha2[2]));
	    		
	    		trabajador.setID(idTrabajador);
	    		trabajador.setNombre(nombreAc.getText());
	    		trabajador.setApellidos(apellidosAc.getText());
	    		trabajador.setDNI(dniAc.getText());
	    		trabajador.setFecIni(fechainicio);
	    		trabajador.setFecFin(fechafin); 		
	    		trabajador.setTipo(false);
	    		trabajador.setHoras(Integer.parseInt(horasAc.getText())); //Horas es un textfield modificado para que acepte int
	    		trabajador.setSueldoHoras(Float.parseFloat(sueldo_horasAc.getText()));

				
				Controlador.getInstance().handleRequest(IDEventos.EVENTO_MODIFICAR_TRABAJADOR, trabajador);
				
			}
			else
	    	{
	    		JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
	    	}
    	}
		else
		{
			if (!nombreAc.getText().equals("") 
	    			&& !apellidosAc.getText().equals("")
					&& !dniAc.getText().equals("") 
					&& !fec_finalAc.getText().equals("")
					&& !fec_inicioAc.getText().equals("")
					&& !factor_productividadAc.getText().equals("")
					&& !sueldo_baseAc.getText().equals("")){
	    		
	    		

	    		String fecha[] = fec_inicioAc.getText().split("/");
	    		String fecha2[] = fec_finalAc.getText().split("/");
	    		java.sql.Date fechainicio = new java.sql.Date(0);
	    		fechainicio.setDate(Integer.valueOf(fecha[0]));
	    		fechainicio.setMonth(Integer.valueOf(fecha[1]));
	    		fechainicio.setYear(Integer.valueOf(fecha[2]));
	    		
	    		java.sql.Date fechafin = new java.sql.Date(0);
	    		fechafin.setDate(Integer.valueOf(fecha2[0]));
	    		fechafin.setMonth(Integer.valueOf(fecha2[1]));
	    		fechafin.setYear(Integer.valueOf(fecha2[2]));
	    		
	    		trabajador.setID(idTrabajador);
	    		trabajador.setNombre(nombreAc.getText());
	    		trabajador.setApellidos(apellidosAc.getText());
	    		trabajador.setDNI(dniAc.getText());
	    		trabajador.setFecIni(fechainicio);
	    		trabajador.setFecFin(fechafin); 		
	    		trabajador.setTipo(true);
	    		trabajador.setFactProd(Float.parseFloat(factor_productividadAc.getText())); //Horas es un textfield modificado para que acepte int
	    		trabajador.setSueldoBase(Float.parseFloat(sueldo_baseAc.getText()));
	    		
	    		Controlador.getInstance().handleRequest(IDEventos.EVENTO_MODIFICAR_TRABAJADOR, trabajador);
	    	}	
			else
	    	{
	    		JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar todos los campos", "Aviso", JOptionPane.WARNING_MESSAGE);
	    	}
		}
    }

    
    ////////////////////// CONSULTAR TRABAJADOR /////////////////////                                 
    private void enviarC1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	
    	String id= idBuscarTrabajadorC.getText();
    	
    	if ( !id.equals("") ) {
			Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_TRABAJADOR, Integer.valueOf(id));
    	}
    	else
    	{
    		JFrame frame = new JFrame();
    		JOptionPane.showMessageDialog(frame,"Tienes que rellenar el ID", "Aviso", JOptionPane.WARNING_MESSAGE);
    	}
    }                                        

    
    ////////////// CONSULTAR N TRABAJADORES ///////////////////
    private void enviarCNActionPerformed(java.awt.event.ActionEvent evt){
    	
		Controlador.getInstance().handleRequest(IDEventos.EVENTO_CONSULTA_TODOS_TRABAJADORES, null);
    }


    public void actualizarVentanaAlta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_ALTA_EMPLEADO == idEvento ) {
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
			    	nombreA.setText("");
					apellidosA.setText("");
					dniA.setText("");
					fec_finalA.setText("");
					fec_inicioA.setText("");
					sueldo_horasA.setText("");
					horasA.setText("");
					
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Empleado creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al crear el empleado", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}
		}
		else if ( IDEventos.ERROR_EVENTO_ALTA_EMPLEADO == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		else if ( IDEventos.EVENTO_ALTA_ENCARGADO == idEvento ) {
			
			if(datos instanceof Boolean)
			{
				Boolean correcto = (Boolean) datos;
				if (correcto) {
					
					nombreA.setText("");
					apellidosA.setText("");
					dniA.setText("");
					fec_finalA.setText("");
					fec_inicioA.setText("");
					factor_productividadA.setText("");
					sueldo_baseA.setText("");
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame,"Encargado creado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
					
				}
				else {
					JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Error al crear el encargado", "Error", JOptionPane.ERROR_MESSAGE);
				}
			}

		}
		else if ( IDEventos.ERROR_EVENTO_ALTA_ENCARGADO == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {

				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
				JOptionPane.showMessageDialog(frame, "Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		
	}

    public void actualizarVentanaConsulta(IDEventos idEvento, Object datos) {
		
		if ( IDEventos.EVENTO_CONSULTA_TRABAJADOR == idEvento ) {
		
			if ( datos instanceof TransferTrabajador) {
				
				TransferTrabajador trabajador = (TransferTrabajador) datos;
				
				if ( trabajador != null ) {
					
					String fecha=""; 
					String fecha2="";
					java.sql.Date fechainicio = trabajador.getFecIni();
					fecha+= fechainicio.getDay();
					fecha+="/";
					fecha+= fechainicio.getMonth();
					fecha+="/";
					fecha+= fechainicio.getYear();


					java.sql.Date fechafin = trabajador.getFecFin();
					fecha2+= fechafin.getDay();
					fecha2+="/";
					fecha2+= fechafin.getMonth();
					fecha2+="/";
					fecha2+= fechafin.getYear();

					nombreC1.setText(trabajador.getNombre());
					apellidosC1.setText(trabajador.getApellidos());
					dniC1.setText(trabajador.getDNI());
					fec_inicioC1.setText(fecha);
					fec_finalC1.setText(fecha2);
					horasC1.setText(trabajador.getHoras().toString());
					sueldo_horasC1.setText(trabajador.getSueldoHoras().toString());
					factor_productividadC1.setText(trabajador.getFactProd().toString());
					tipoTrabajadorC1.setSelected(trabajador.getTipo());
					sueldo_baseC1.setText(trabajador.getSueldoBase().toString());
					
				}
					
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar el trabajador", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
		else if ( IDEventos.ERROR_EVENTO_CONSULTA_TRABAJADOR == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
	}

    public void actualizarVentanaBorra(IDEventos idEvento, Object datos){
    	
    	if ( IDEventos.EVENTO_BAJA_TRABAJADOR == idEvento ) {

    		if ( datos instanceof Boolean ) {

    			Boolean correcto = (Boolean) datos;

    			if (correcto) {
    				
    				idBuscarTrabajadorB.setText("");
    				idTrabajador = null;
    				dniB.setText("");
    				nombreB.setText("");
    				apellidosB.setText("");
    				fec_finalB.setText("");
    				fec_inicioB.setText("");
    				factor_productividadB.setText("");
    				sueldo_baseB.setText("");
    				sueldo_horasB.setText("");
    				horasB.setText("");
    				tipoTrabajadorB.setSelected(false);
    				borraB.setEnabled(false);

    				JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"Trabajador borrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    			}
    			else {

    				JFrame frame = new JFrame();
		    		JOptionPane.showMessageDialog(frame,"El trabajador no se ha borrado", "Error", JOptionPane.ERROR_MESSAGE);
    			}
    		}
    	}
    	else if (IDEventos.EVENTO_CONSULTAR_TRABAJADOR_BORRAR == idEvento) {

    		if ( datos instanceof TransferTrabajador) {

    			TransferTrabajador trabajador = (TransferTrabajador) datos;

    			idTrabajador = trabajador.getID();
    			
    			String fecha=""; 
				String fecha2="";
				java.sql.Date fechainicio = trabajador.getFecIni();
				fecha+= fechainicio.getDay();
				fecha+="/";
				fecha+= fechainicio.getMonth();
				fecha+="/";
				fecha+= fechainicio.getYear();


				java.sql.Date fechafin = trabajador.getFecFin();
				fecha2+= fechafin.getDay();
				fecha2+="/";
				fecha2+= fechafin.getMonth();
				fecha2+="/";
				fecha2+= fechafin.getYear();

				nombreB.setText(trabajador.getNombre());
				apellidosB.setText(trabajador.getApellidos());
				dniB.setText(trabajador.getDNI());
				fec_inicioB.setText(fecha);
				fec_finalB.setText(fecha2);
				horasB.setText(trabajador.getHoras().toString());
				sueldo_horasB.setText(trabajador.getSueldoHoras().toString());
				factor_productividadB.setText(trabajador.getFactProd().toString());
				tipoTrabajadorB.setSelected(trabajador.getTipo());
				sueldo_baseB.setText(trabajador.getSueldoBase().toString());
    			borraB.setEnabled(true);
    		}
    	}
    	else if ( IDEventos.ERROR_EVENTO_BAJA_TRABAJADOR == idEvento || IDEventos.ERROR_EVENTO_CONSULTAR_TRABAJADOR_BORRAR == idEvento ) {

    		if ( datos instanceof ExcepcionSQL ) {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		else {
    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }

    public void actualizarVentanaActualiza(IDEventos idEvento, Object datos){
	    
    	if ( IDEventos.EVENTO_MODIFICAR_TRABAJADOR == idEvento ) {
			
			if ( datos instanceof Boolean ) {
				
				Boolean correcto = (Boolean) datos;
				
				if (correcto) {
					
					idBuscarTrabajadorAc.setText("");
					idBuscarTrabajadorAc.setEditable(false);
					
					nombreAc.setText("");
					nombreAc.setEditable(false);
					apellidosAc.setText("");
					apellidosAc.setEditable(false);
					dniAc.setText("");
					dniAc.setEditable(false);
					fec_finalAc.setText("");
					fec_finalAc.setEditable(false);
					fec_inicioAc.setText("");
					fec_inicioAc.setEditable(false);
					sueldo_baseAc.setText("");
					sueldo_baseAc.setEditable(false);
					sueldo_horasAc.setText("");
					sueldo_horasAc.setEditable(false);
					factor_productividadAc.setText("");
					factor_productividadAc.setEditable(false);
					horasAc.setText("");
					horasAc.setEditable(false);
					tipoTrabajadorAc.setSelected(false);
					
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame, "Trabajador modificado", "Aviso", JOptionPane.INFORMATION_MESSAGE);
				}
				else {
					
					JFrame frame = new JFrame();
					JOptionPane.showMessageDialog(frame, "El trabajador no se ha modificado", "Error", JOptionPane.ERROR_MESSAGE);
				}
				idTrabajador = null;
			}
		}
		else if ( IDEventos.EVENTO_CONSULTAR_TRABAJADOR_MODIFICAR == idEvento ) {
			
			if ( datos instanceof TransferTrabajador) {

    			TransferTrabajador trabajador = (TransferTrabajador) datos;

    			idTrabajador = trabajador.getID();
    			
    			String fecha=""; 
				String fecha2="";
				java.sql.Date fechainicio = trabajador.getFecIni();
				fecha+= fechainicio.getDay();
				fecha+="/";
				fecha+= fechainicio.getMonth();
				fecha+="/";
				fecha+= fechainicio.getYear();


				java.sql.Date fechafin = trabajador.getFecFin();
				fecha2+= fechafin.getDay();
				fecha2+="/";
				fecha2+= fechafin.getMonth();
				fecha2+="/";
				fecha2+= fechafin.getYear();

				nombreAc.setText(trabajador.getNombre());
				apellidosAc.setText(trabajador.getApellidos());
				dniAc.setText(trabajador.getDNI());
				fec_inicioAc.setText(fecha);
				fec_finalAc.setText(fecha2);
				horasAc.setText(trabajador.getHoras().toString());
				sueldo_horasAc.setText(trabajador.getSueldoHoras().toString().toString());
				factor_productividadAc.setText(trabajador.getFactProd().toString());
				tipoTrabajadorAc.setSelected(trabajador.getTipo());
				sueldo_baseAc.setText(trabajador.getSueldoBase().toString());
    			actualizaAc.setEnabled(true);
    			
				nombreAc.setEditable(true);
				apellidosAc.setEditable(true);
				dniAc.setEditable(true);
				fec_finalAc.setEditable(true);
				fec_inicioAc.setEditable(true);
				sueldo_baseAc.setEditable(true);
				sueldo_horasAc.setEditable(true);
				factor_productividadAc.setEditable(true);
				horasAc.setEditable(true);
				tipoTrabajadorAc.setEnabled(true);
    			
    		}
		}
		else if ( IDEventos.ERROR_EVENTO_MODIFICAR_TRABAJADOR == idEvento || IDEventos.ERROR_EVENTO_CONSULTAR_TRABAJADOR_MODIFICAR == idEvento ) {
			
			if ( datos instanceof ExcepcionSQL ) {
				
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
			}
			else {
				JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
			}
		}
    }

    public void actualizarVentanaConsultaN(IDEventos idEvento, Object datos) {

    	if ( IDEventos.EVENTO_CONSULTA_TODOS_TRABAJADORES == idEvento ) {

    		if ( datos instanceof List) {

    			@SuppressWarnings("unchecked")
    			List<TransferTrabajador> listaTrabajador = (List<TransferTrabajador>) datos;

    			TransferTrabajador[] trabajador = new TransferTrabajador[listaTrabajador.size()];
    			listaTrabajador.toArray(trabajador);
    			list.setListData(trabajador);

    			//Como ponerlo aqui?
    		}
    		else {
    			JFrame frame = new JFrame();
	    		JOptionPane.showMessageDialog(frame,"Error al consultar todos los trabajadores", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    	else if ( IDEventos.ERROR_CONSULTA_TODOS_TRABAJADORES == idEvento ) {

    		if ( datos instanceof ExcepcionSQL ) {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,((ExcepcionSQL)datos).getMensaje(), "Error", JOptionPane.ERROR_MESSAGE);
    		}
    		else {

    			JFrame frame = new JFrame();
    			JOptionPane.showMessageDialog(frame,"Error genérico", "Error", JOptionPane.ERROR_MESSAGE);
    		}
    	}
    }
    
    
    private void botones(){
    	
    	fec_finalA.setVisible(true);
        etiqFec_finalA.setVisible(true);
        fec_inicioA.setVisible(true);
        etiqFec_inicioA.setVisible(true);
        dniA.setVisible(true);
        etiqDNIA.setVisible(true);
        etiqApellidosA.setVisible(true);
        apellidosA.setVisible(true);
        nombreA.setVisible(true);
        etiqNombreA.setVisible(true);
        etiqSueldo_horasA.setVisible(true);
        sueldo_horasA.setVisible(true);
        horasA.setVisible(true);
        etiqHorasA.setVisible(true);
        sueldo_baseA.setVisible(false);
        etiqSueldo_baseA.setVisible(false);
        factor_productividadA.setVisible(false);
        etiqFactor_productividadA.setVisible(false);
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton actualizaAc;
    private javax.swing.JPanel actualizarTrabajador;
    private javax.swing.JPanel altaTrabajador;
    private javax.swing.JTextField apellidosA;
    private javax.swing.JTextField apellidosAc;
    private javax.swing.JTextField apellidosB;
    private javax.swing.JTextField apellidosC1;
    private javax.swing.JPanel bajaTrabajador;
    private javax.swing.JButton borraB;
    private javax.swing.JPanel consultaNTrabajador;
    private javax.swing.JPanel consultaTrabajador;
    private javax.swing.JTextField dniA;
    private javax.swing.JTextField dniAc;
    private javax.swing.JTextField dniB;
    private javax.swing.JTextField dniC1;
    private javax.swing.JButton enviarA;
    private javax.swing.JButton enviarAc;
    private javax.swing.JButton enviarB;
    private javax.swing.JButton enviarC1;
    private javax.swing.JButton enviarCN;
    private javax.swing.JLabel etiqApellidosA;
    private javax.swing.JLabel etiqApellidosAc;
    private javax.swing.JLabel etiqApellidosC;
    private javax.swing.JLabel etiqApellidosC1;
    private javax.swing.JLabel etiqApellidosCN;
    private javax.swing.JLabel etiqDNIA;
    private javax.swing.JLabel etiqDNIB;
    private javax.swing.JLabel etiqdniC1;
    private javax.swing.JLabel etiqDNIB2;
    private javax.swing.JLabel etiqEmailCN;
    private javax.swing.JLabel etiqFactor_productividadA;
    private javax.swing.JLabel etiqFactor_productividadA1;
    private javax.swing.JLabel etiqFactor_productividadA2;
    private javax.swing.JLabel etiqFactor_productividadC1;
    private javax.swing.JLabel etiqFec_finalA;
    private javax.swing.JLabel etiqFec_finalAc;
    private javax.swing.JLabel etiqFec_finalB;
    private javax.swing.JLabel etiqFec_finalC1;
    private javax.swing.JLabel etiqFec_inicioA;
    private javax.swing.JLabel etiqFec_inicioA1;
    private javax.swing.JLabel etiqFec_inicioA2;
    private javax.swing.JLabel etiqFec_inicioC1;
    private javax.swing.JLabel etiqHorasA;
    private javax.swing.JLabel etiqHorasAc;
    private javax.swing.JLabel etiqHorasB;
    private javax.swing.JLabel etiqHorasC1;
    private javax.swing.JLabel etiqIDAc;
    private javax.swing.JLabel etiqIDB;
    private javax.swing.JLabel etiqIDC;
    private javax.swing.JLabel etiqIDCN;
    private javax.swing.JLabel etiqNombreA;
    private javax.swing.JLabel etiqNombreAc;
    private javax.swing.JLabel etiqNombreB;
    private javax.swing.JLabel etiqNombreC1;
    private javax.swing.JLabel etiqNombreCN;
    private javax.swing.JLabel etiqSueldo_baseA;
    private javax.swing.JLabel etiqSueldo_baseA1;
    private javax.swing.JLabel etiqSueldo_baseAc;
    private javax.swing.JLabel etiqSueldo_baseC1;
    private javax.swing.JLabel etiqSueldo_horasA;
    private javax.swing.JLabel etiqSueldo_horasA1;
    private javax.swing.JLabel etiqSueldo_horasAc;
    private javax.swing.JLabel etiqSueldo_horasC1;
    private javax.swing.JLabel etiqTelefonoCN;
    private javax.swing.JTextField factor_productividadA;
    private javax.swing.JTextField factor_productividadAc;
    private javax.swing.JTextField factor_productividadB;
    private javax.swing.JTextField factor_productividadC1;
    private javax.swing.JFormattedTextField fec_finalA;
    private javax.swing.JFormattedTextField fec_finalAc;
    private javax.swing.JFormattedTextField fec_finalB;
    private javax.swing.JFormattedTextField fec_finalC1;
    private javax.swing.JFormattedTextField fec_inicioA;
    private javax.swing.JFormattedTextField fec_inicioAc;
    private javax.swing.JFormattedTextField fec_inicioB;
    private javax.swing.JFormattedTextField fec_inicioC1;
    private javax.swing.JTextField horasA;
    private javax.swing.JTextField horasAc;
    private javax.swing.JTextField horasB;
    private javax.swing.JTextField horasC1;
    private javax.swing.JTextField idBuscarTrabajadorAc;
    private javax.swing.JTextField idBuscarTrabajadorB;
    private javax.swing.JTextField idBuscarTrabajadorC;
    private javax.swing.JSeparator lineaB1;
    private javax.swing.JSeparator lineaB2;
    private javax.swing.JSeparator lineaB3;
    private javax.swing.JTextField nombreA;
    private javax.swing.JTextField nombreAc;
    private javax.swing.JTextField nombreB;
    private javax.swing.JTextField nombreC1;
    private javax.swing.JButton nuevaAc;
    private javax.swing.JTabbedPane panelTrabajador;
    private javax.swing.JScrollPane scrollConsultaN;
    private javax.swing.JTextField sueldo_baseA;
    private javax.swing.JTextField sueldo_baseAc;
    private javax.swing.JTextField sueldo_baseB;
    private javax.swing.JTextField sueldo_baseC1;
    private javax.swing.JTextField sueldo_horasA;
    private javax.swing.JTextField sueldo_horasAc;
    private javax.swing.JTextField sueldo_horasB;
    private javax.swing.JTextField sueldo_horasC1;
    private javax.swing.JComboBox tipoA;
    private javax.swing.JCheckBox tipoTrabajadorAc;
    private javax.swing.JCheckBox tipoTrabajadorB;
    private javax.swing.JCheckBox tipoTrabajadorC1;
    private JList<TransferTrabajador> list;
    private String valor;
    private Integer idTrabajador;
    // End of variables declaration                   

}
